User tinyproxy
Group tinyproxy
Port 4188
Listen 127.0.0.1
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/openreel-youtube.log"
LogLevel Info
PidFile "/run/tinyproxy/openreel-youtube.pid"
MaxClients 20
Allow 127.0.0.1
ConnectPort 443
DisableViaHeader Yes
