import { NODE_TYPES } from "./model.js";
import { TUTORIALS, tutorialById, tutorialProgress } from "./tutorials.js";
import { activeStoryboardJob, retryableStoryboardJob, storyboardBatchView } from "./storyboard-batch-ui.js";
import { modelControlView, selectedModelControls } from "./model-controls.js";
import { collaborationConflictView } from "./collaboration-ui.js";
import { reviewedExportSelection, exportSuccessMessage } from "./export-ui.js";
import { isQwenTtsModel, prepareQwenTtsJob, qwenTtsPreparedMessage } from "./qwen-tts-ui.js";

const icons = { text: "T", image: "▧", video: "▶", audio: "♪", script: "≡" };
let snapshot = { nodes: [], edges: [], groups: [] }, models = [], selected = [], selectedGraph = null, storyboardBatch = null, view = { x: 0, y: 0, scale: 1 }, projectId, sessionId, csrfToken = "", workspaceStarted = false;
const $ = selector => document.querySelector(selector), viewport = $("#viewport"), canvas = $("#canvas"), nodeForm = $("#node-form"), graphForm = $("#graph-form");

$("#node-tools").replaceChildren(...NODE_TYPES.map(type => button(type, async () => {
  const rect = viewport.getBoundingClientRect(), position = { x: (rect.width / 2 - view.x) / view.scale - 120, y: (rect.height / 2 - view.y) / view.scale - 70 };
  const node = await api(`/api/v1/sessions/${sessionId}/nodes`, json("POST", { type, position })); await refresh(node.id);
})));

function button(label, action) { const element = document.createElement("button"); element.className = "tool"; element.innerHTML = `<span>${icons[label] || "+"}</span>${label}`; element.addEventListener("click", () => action().catch(showError)); return element; }
async function refresh(selectId) { snapshot = await api(`/api/v1/projects/${projectId}`); if (selectId) selected = [selectId]; render(); }
function render() {
  canvas.style.transform = `translate(${view.x}px, ${view.y}px) scale(${view.scale})`;
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.classList.add("edges");
  for (const edge of snapshot.edges) { const from = snapshot.nodes.find(n => n.id === edge.fromNodeId), to = snapshot.nodes.find(n => n.id === edge.toNodeId); if (!from || !to) continue; const line = document.createElementNS(svg.namespaceURI, "line"); line.setAttribute("x1", from.position.x + 120); line.setAttribute("y1", from.position.y + 60); line.setAttribute("x2", to.position.x + 120); line.setAttribute("y2", to.position.y + 60); line.dataset.edgeId = edge.id; line.addEventListener("click", event => { event.stopPropagation(); selectedGraph = { kind: "edge", value: edge }; selected = []; render(); }); svg.append(line); }
  canvas.replaceChildren(...snapshot.groups.map(renderGroup), svg, ...snapshot.nodes.map(renderNode));
  const node = snapshot.nodes.find(item => item.id === selected.at(-1));
  $("#inspector-empty").hidden = Boolean(node || selectedGraph); nodeForm.hidden = !node; graphForm.hidden = !selectedGraph;
  if (node) { $("#node-title").value = node.title; $("#node-content").value = node.content; $("#node-meta").textContent = `${node.type} · ${Math.round(node.position.x)}, ${Math.round(node.position.y)} · ${node.status} · v${node.version}`; $("#generation-panel").hidden = !["image", "video", "audio"].includes(node.type); if (!$("#generation-panel").hidden) renderParameters(node.type); $("#node-history").replaceChildren(...node.runs.map(run => { const li = document.createElement("li"); li.textContent = `${run.state} · ${run.events.length} events · ${run.error?.code || run.assetId || "pending"}`; return li; }), ...node.resultVersions.map(result => { const li = document.createElement("li"); const link = document.createElement("a"); link.href = result.downloadUrl; link.textContent = `result ${result.id}`; li.append(link); return li; })); }
  if (selectedGraph) { $("#graph-title").value = selectedGraph.value.title || ""; $("#graph-meta").textContent = `${selectedGraph.kind} · v${selectedGraph.value.version}`; }
  $("#zoom-label").value = `${Math.round(view.scale * 100)}%`;
}
function renderNode(node) { const element = document.createElement("article"); element.className = `node node-${node.type}${selected.includes(node.id) ? " selected" : ""}`; element.dataset.nodeId = node.id; element.style.transform = `translate(${node.position.x}px, ${node.position.y}px)`; const audio = node.resultVersions.find(result => result.mimeType?.startsWith("audio/")); element.innerHTML = `<header><span>${icons[node.type]}</span><strong>${escapeHtml(node.title)}</strong><small>${node.type}</small></header><p>${escapeHtml(node.content)}</p>${audio ? `<audio controls preload="metadata" src="${escapeHtml(audio.downloadUrl)}" aria-label="${escapeHtml(node.title)} preview"></audio>` : ""}<footer data-state="${node.status}"><i></i>${node.status}</footer>`; element.addEventListener("click", event => { event.stopPropagation(); selectedGraph = null; selected = event.shiftKey ? [...new Set([...selected, node.id])] : [node.id]; render(); }); element.addEventListener("pointerdown", event => { if (event.target.closest("audio")) return; dragNode(event, node); }); return element; }
function renderGroup(group) { const members = snapshot.nodes.filter(node => group.nodeIds.includes(node.id)); const element = document.createElement("section"); element.className = "graph-group"; element.dataset.groupId = group.id; const minX = Math.min(...members.map(n => n.position.x)) - 24, minY = Math.min(...members.map(n => n.position.y)) - 44, maxX = Math.max(...members.map(n => n.position.x + 240)) + 24, maxY = Math.max(...members.map(n => n.position.y + 120)) + 24; Object.assign(element.style, { transform: `translate(${minX}px, ${minY}px)`, width: `${maxX-minX}px`, height: `${maxY-minY}px` }); element.textContent = group.title; element.addEventListener("click", event => { event.stopPropagation(); selectedGraph = { kind: "group", value: group }; selected = []; render(); }); return element; }
function dragNode(event, node) { if (event.button !== 0) return; const start = { clientX: event.clientX, clientY: event.clientY, ...node.position }; const move = next => { node.position = { x: start.x + (next.clientX-start.clientX)/view.scale, y: start.y + (next.clientY-start.clientY)/view.scale }; render(); }; const end = async () => { window.removeEventListener("pointermove", move); await api(`/api/v1/nodes/${node.id}`, json("PATCH", { position: node.position, version: node.version })); await refresh(node.id); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }

$("#create-edge").addEventListener("click", async () => { if (selected.length !== 2) return showError(new Error("Select exactly two nodes (Shift-click)")); await api(`/api/v1/projects/${projectId}/edges`, json("POST", { fromNodeId: selected[0], toNodeId: selected[1] })); await refresh(); });
$("#create-group").addEventListener("click", async () => { if (selected.length < 1) return showError(new Error("Select one or more nodes")); await api(`/api/v1/projects/${projectId}/groups`, json("POST", { title: "New group", nodeIds: selected })); await refresh(); });
nodeForm.addEventListener("change", async event => { if (!event.target.matches("#node-title, #node-content")) return; const node = snapshot.nodes.find(item => item.id === selected.at(-1)); if (!node) return; await api(`/api/v1/nodes/${node.id}`, json("PATCH", { title: $("#node-title").value, content: $("#node-content").value, version: node.version })); await refresh(node.id); });
graphForm.addEventListener("change", async () => { const graph = selectedGraph; await api(`/api/v1/${graph.kind}s/${graph.value.id}`, json("PATCH", { title: $("#graph-title").value, version: graph.value.version })); snapshot = await api(`/api/v1/projects/${projectId}`); selectedGraph = { kind: graph.kind, value: snapshot[`${graph.kind}s`].find(item => item.id === graph.value.id) }; render(); });

viewport.addEventListener("pointerdown", event => { if (event.target !== viewport && event.target !== canvas) return; selected = []; selectedGraph = null; const start = { clientX: event.clientX, clientY: event.clientY, ...view }; const move = next => { view.x = start.x + next.clientX-start.clientX; view.y = start.y + next.clientY-start.clientY; render(); }; const end = () => window.removeEventListener("pointermove", move); window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); render(); });
viewport.addEventListener("wheel", event => { event.preventDefault(); setScale(view.scale * (event.deltaY < 0 ? 1.1 : .9)); }, { passive: false });
$("#zoom-in").onclick = () => setScale(view.scale + .1); $("#zoom-out").onclick = () => setScale(view.scale - .1); function setScale(scale) { view.scale = Math.min(2, Math.max(.4, scale)); render(); }
$("#reload-collaboration").onclick = async () => { await refresh(); $("#collaboration-conflict").hidden = true; };
$("#rename-project").onclick = async () => { const name = prompt("Project name", snapshot.project.name); if (name) { await api(`/api/v1/projects/${projectId}`, json("PATCH", { name, version: snapshot.project.version })); await refresh(); } };
$("#archive-project").onclick = async () => { await api(`/api/v1/projects/${projectId}`, json("PATCH", { status: "archived", version: snapshot.project.version })); await refresh(); };
$("#api-access").onclick = async () => { $("#api-access-dialog").showModal(); await refreshKeyApplications(); };
$("#tutorials").onclick = () => { renderTutorialList(); $("#tutorial-dialog").showModal(); };
function renderTutorialList() {
  $("#tutorial-detail").hidden = true; $("#tutorial-list").hidden = false;
  $("#tutorial-list").replaceChildren(...TUTORIALS.map(tutorial => {
    const card = document.createElement("button"); card.type = "button"; card.className = "tutorial-card";
    card.innerHTML = `<span>${escapeHtml(tutorial.category)} · ${escapeHtml(tutorial.level)}</span><strong>${escapeHtml(tutorial.title)}</strong><small>${escapeHtml(tutorial.duration)} · ${escapeHtml(tutorial.calls)}</small><p>${escapeHtml(tutorial.outcome)}</p>`;
    card.onclick = () => renderTutorial(tutorial.id); return card;
  }));
}
async function renderTutorial(id) {
  const tutorial = tutorialById(id), detail = $("#tutorial-detail"); $("#tutorial-list").hidden = true; detail.hidden = false;
  const key = `openreel:tutorial:${projectId}:${tutorial.id}:v${tutorial.version}`; let saved = [];
  try { saved = JSON.parse(localStorage.getItem(key) || "[]"); } catch { localStorage.removeItem(key); }
  try { tutorialProgress(tutorial.id, saved); } catch { localStorage.removeItem(key); saved = []; }
  let progress = await api(`/api/v1/projects/${projectId}/tutorials/${tutorial.id}/progress`);
  if (saved.length && !progress.completedSteps.length) { progress = await api(`/api/v1/projects/${projectId}/tutorials/${tutorial.id}/progress`, json("PUT", { completedSteps: saved })); localStorage.removeItem(key); }
  const references = snapshot.assets.filter(asset => asset.sessionId === sessionId && asset.kind === "image" && asset.role === "reference"), shortcuts = (await api("/api/v1/workflow-shortcuts")).templates;
  detail.innerHTML = `<button class="tutorial-back" type="button">← 全部教程</button><p class="eyebrow">${escapeHtml(tutorial.category)} · ${escapeHtml(tutorial.level)}</p><h2>${escapeHtml(tutorial.title)}</h2><p class="tutorial-outcome">${escapeHtml(tutorial.outcome)}</p><div class="tutorial-meta"><span>${escapeHtml(tutorial.duration)}</span><span>${escapeHtml(tutorial.calls)}</span><span>${tutorial.nodes.length} 个节点</span><span>v${tutorial.version}</span></div><h3>操作步骤</h3><ol class="tutorial-steps">${tutorial.steps.map((step, index) => `<li><label><input type="checkbox" value="${index}"${progress.completedSteps.includes(index) ? " checked" : ""}>${escapeHtml(step)}</label></li>`).join("")}</ol><p class="tutorial-progress" role="status">${progress.completedCount}/${progress.totalSteps} 步完成 · ${progress.status}</p><h3>验收清单</h3><ul>${tutorial.checks.map(check => `<li>${escapeHtml(check)}</li>`).join("")}</ul><section class="tutorial-shortcut"><h3>经审查的快捷模板</h3><label>模板<select>${shortcuts.map(item => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.label)}</option>`).join("")}</select></label><label>参考图<select class="tutorial-reference"><option value="">选择已上传参考图</option>${references.map(asset => `<option value="${escapeHtml(asset.id)}">${escapeHtml(asset.filename)}</option>`).join("")}</select></label><label>创作要求<textarea rows="3"></textarea></label><button type="button"${references.length ? "" : " disabled"}>创建待审阅节点</button><p role="status">${references.length ? "不会自动生成或产生费用。" : "请先上传一张图片参考素材。"}</p></section><p class="tutorial-safety">开始教程只会创建并连接节点，不会提交模型任务或产生费用。请在生成前检查模型、参数和管理员额度。</p><button class="tutorial-start" type="button">把教程蓝图放到当前画布</button>`;
  detail.querySelector(".tutorial-back").onclick = renderTutorialList;
  detail.querySelector(".tutorial-steps").onchange = async () => { const completedSteps = [...detail.querySelectorAll(".tutorial-steps input:checked")].map(input => Number(input.value)), next = await api(`/api/v1/projects/${projectId}/tutorials/${tutorial.id}/progress`, json("PUT", { completedSteps })); detail.querySelector(".tutorial-progress").textContent = `${next.completedCount}/${next.totalSteps} 步完成 · ${next.status}`; };
  detail.querySelector(".tutorial-shortcut button").onclick = async event => { const section = event.currentTarget.closest(".tutorial-shortcut"), shortcutId = section.querySelector("select").value, referenceAssetId = section.querySelector(".tutorial-reference").value, prompt = section.querySelector("textarea").value; event.currentTarget.disabled = true; try { const node = await api(`/api/v1/projects/${projectId}/sessions/${sessionId}/workflow-shortcuts/${shortcutId}/apply`, json("POST", { prompt, referenceAssetIds: [referenceAssetId] })); await refresh(node.id); section.querySelector("[role=status]").textContent = "待审阅节点已创建；尚未运行。"; } finally { event.currentTarget.disabled = false; } };
  detail.querySelector(".tutorial-start").onclick = event => startTutorial(tutorial, event.currentTarget).catch(showError);
}
async function startTutorial(tutorial, trigger) {
  trigger.disabled = true;
  try {
    const workflow = await api(`/api/v1/tutorials/${tutorial.id}/workflow`);
    const created = [];
    for (const spec of workflow.nodes) {
      const node = await api(`/api/v1/sessions/${sessionId}/nodes`, json("POST", { type: spec.type, position: spec.position }));
      created.push(await api(`/api/v1/nodes/${node.id}`, json("PATCH", { title: spec.title, content: spec.content, version: node.version })));
    }
    for (let index = 1; index < created.length; index += 1) await api(`/api/v1/projects/${projectId}/edges`, json("POST", { fromNodeId: created[index - 1].id, toNodeId: created[index].id }));
    await api(`/api/v1/projects/${projectId}/groups`, json("POST", { title: `Tutorial · ${tutorial.title}`, nodeIds: created.map(node => node.id) }));
    await refresh(created[0].id); $("#tutorial-dialog").close(); $("#workflow-state").textContent = `Tutorial ready: ${tutorial.title}. Review each prompt before generating.`;
  } finally { trigger.disabled = false; }
}
$("#key-application-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await api("/api/v1/key-applications", json("POST", { reason: $("#key-application-reason").value, requestedLimitUnits: Math.round(Number($("#key-application-limit").value) * 10000), currency: "USD", unitScale: 10000 })); event.target.reset(); await refreshKeyApplications(); } catch (error) { $("#key-application-state").textContent = `Error: ${error.message}`; } finally { button.disabled = false; } });
$("#create-api-key").onclick = async () => { const issued = await api("/api/v1/api-keys", json("POST", { name: "primary" })); $("#issued-key").textContent = `Copy now — this external API key will not be shown again: ${issued.key}`; await refreshKeyApplications(); };
async function refreshKeyApplications() { const [applications, keys] = await Promise.all([api("/api/v1/key-applications"), api("/api/v1/api-keys")]); $("#key-application-state").textContent = applications.length ? "Your application history" : "No application submitted yet."; $("#key-application-list").replaceChildren(...[...applications].reverse().map(item => { const li = document.createElement("li"); li.textContent = `${item.status} · limit ${money(item.requestedLimitUnits ?? item.requestedLimitMicros, item.currency, item.unitScale)} · ${item.reason}${item.reviewNote ? ` · ${item.reviewNote}` : ""}`; return li; })); const approved = applications.some(item => item.status === "approved"); $("#key-issue-panel").hidden = !approved; $("#api-key-list").replaceChildren(...keys.map(key => { const li = document.createElement("li"); li.textContent = `${key.name} · ${key.prefix}… · ${key.status}`; return li; })); }
function money(units, currency = "CNY", scale = 1_000_000) { return new Intl.NumberFormat("en-US", { style: "currency", currency, minimumFractionDigits: 4, maximumFractionDigits: 4 }).format(Number(units || 0) / scale); }
$("#generate").onclick = async () => { const node = snapshot.nodes.find(item => item.id === selected.at(-1)), chosen = models.find(x => x.id === $("#generation-model").value), value = id => $(id).value || undefined, selectedControls = [...document.querySelectorAll("#generation-controls input:checked")].map(input => input.value), audioSpec = node.type === "audio" ? { intent: value("#audio-intent"), ...(value("#audio-intent") === "voice" && value("#audio-voice") ? { voice: value("#audio-voice"), speed: Number(value("#audio-speed")), pitch: Number(value("#audio-pitch")), volume: Number(value("#audio-volume")) } : {}), sampleRate: Number(value("#audio-sample-rate")), format: value("#audio-format") } : undefined, parameters = { mode: value("#generation-mode"), aspect: value("#generation-aspect"), resolution: value("#generation-resolution"), duration: value("#generation-duration") ? Number(value("#generation-duration")) : undefined, audio: chosen.schema.audio === undefined ? undefined : $("#generation-audio").checked, controls: selectedModelControls(chosen.schema, selectedControls), ...(audioSpec && { audioSpec, reviewed: $("#audio-reviewed").checked }) }; let job; if (isQwenTtsModel(chosen)) { job = await api(`/api/v1/sessions/${sessionId}/qwen-tts-jobs`, json("POST", prepareQwenTtsJob({ nodeId: node.id, prompt: $("#generation-prompt").value, duration: parameters.duration, audioSpec, reviewed: parameters.reviewed, language: value("#audio-language"), instruct: value("#audio-instruct"), idempotencyKey: crypto.randomUUID() }))); $("#generation-state").textContent = qwenTtsPreparedMessage(job); } else if (chosen.adapterId === "ark") { job = await api(`/api/v1/sessions/${sessionId}/ark-jobs`, json("POST", { nodeId: node.id, prompt: $("#generation-prompt").value, model: chosen.id, capability: node.type, parameters, idempotencyKey: crypto.randomUUID() })); while (!["succeeded","failed"].includes(job.state)) { await new Promise(resolve => setTimeout(resolve, 1000)); job = await api(`/api/v1/jobs/${job.id}/ark-poll`, json("POST", {})); } } else { job = await api(`/api/v1/sessions/${sessionId}/jobs`, json("POST", { nodeId: node.id, prompt: $("#generation-prompt").value, adapterId: chosen.adapterId, ...parameters, outcome: $("#simulate-failure").checked ? "failed" : "succeeded" })); while (!["succeeded","failed","canceled"].includes(job.state)) job = await api(`/api/v1/jobs/${job.id}/tick`, json("POST", {})); } await refresh(node.id); await refreshLibrary(); };
function options(select, values = []) { select.replaceChildren(...values.map(value => { const option = document.createElement("option"); option.value = value; option.textContent = value; return option; })); select.closest("label").hidden = !values.length; }
function renderParameters(kind) { $("#audio-spec-fields").hidden = kind !== "audio"; if (kind !== "audio") $("#audio-reviewed").checked = false; const select = $("#generation-model"), available = models.filter(x => x.kind === kind), previous = select.dataset.initialized === "true" ? select.value : "", current = available.find(x => x.id === previous) || available.find(x => x.adapterId === "ark") || available[0]; options(select, available.map(x => x.id)); select.dataset.initialized = "true"; if (!current) return; select.value = current.id; for (const [field, values] of [["mode", current.schema.modes], ["aspect", current.schema.aspects], ["resolution", current.schema.resolutions], ["duration", current.schema.durations]]) options($(`#generation-${field}`), values); $("#generation-audio").checked = current.schema.audio === true; $("#generation-audio").disabled = current.schema.audio === undefined; const controls = modelControlView(current.schema), container = $("#generation-controls"); container.hidden = !controls.length; container.replaceChildren(...controls.map(control => { const label = document.createElement("label"), input = document.createElement("input"); input.type = "checkbox"; input.value = control.id; label.append(input, control.label); return label; })); $("#reference-limit").textContent = `Up to ${current.schema.maxReferences} references`; const qwen = isQwenTtsModel(current); $("#qwen-fields").hidden = !qwen; $("#generate").textContent = qwen ? "Prepare Qwen voice job" : "Generate locally"; $("#generation-safety").textContent = qwen ? "Preparation stores a queued job only. It cannot call Qwen TTS; execution requires a separate server-side authorization." : "Ark generation uses your signed-in account's approved USD allowance. No platform key is required in the workspace."; }
$("#generation-model").onchange = () => renderParameters(snapshot.nodes.find(x => x.id === selected.at(-1)).type);
async function refreshLibrary() { const query = new URLSearchParams({ search: $("#library-search").value, kind: $("#library-kind").value }), [assets, history] = await Promise.all([api(`/api/v1/projects/${projectId}/assets?${query}`), api(`/api/v1/projects/${projectId}/history?${query}`)]); $("#asset-library").replaceChildren(...assets.map(asset => { const li = document.createElement("li"); li.append(`${asset.kind} · ${asset.filename} · ${asset.metadata?.provenance?.operation || asset.role}`); if (asset.mimeType?.startsWith("audio/")) { const audio = document.createElement("audio"); audio.controls = true; audio.preload = "metadata"; audio.src = asset.downloadUrl; audio.setAttribute("aria-label", `${asset.filename} preview`); li.append(audio); } return li; }), ...history.map(run => { const li = document.createElement("li"); li.textContent = `run · ${run.kind} · ${run.state} · ${run.prompt}`; return li; })); }
$("#library-refresh").onclick = () => refreshLibrary().catch(showError);
$("#reference-upload").onchange = async event => {
  const input = event.currentTarget, file = input.files?.[0];
  if (!file) return;
  const state = $("#upload-state");
  state.textContent = `Uploading ${file.name}…`;
  try {
    const response = await fetch(`/api/v1/projects/${projectId}/sessions/${sessionId}/assets/references`, {
      method: "POST",
      headers: { "content-type": file.type, "x-filename": file.name, ...(csrfToken ? { "x-csrf-token": csrfToken } : {}) },
      body: file
    });
    const value = await response.json();
    if (!response.ok) { const error = new Error(value.error?.message || "Upload failed"); error.code = value.error?.code; throw error; }
    state.textContent = `Uploaded: ${value.filename} · ${value.kind} · ${value.byteLength} bytes`;
    await refresh();
    await refreshLibrary();
  } catch (error) {
    state.textContent = `Error: ${error.code ? `${error.code}: ` : ""}${error.message}`;
  } finally {
    input.value = "";
  }
};
$("#build-story").onclick = async () => { const story = await api(`/api/v1/projects/${projectId}/story`, json("PUT", { title: "Local demo", scenes: [{ title: "Opening" }] })); await api(`/api/v1/projects/${projectId}/storyboard`, json("PUT", { shots: [{ sceneId: story.scenes[0].id, prompt: "Opening", duration: 1 }] })); $("#workflow-state").textContent = "Success: story and shot persisted."; };
function renderStoryboardBatch() { const value = storyboardBatchView(storyboardBatch); $("#storyboard-batch").hidden = !storyboardBatch; $("#storyboard-batch-state").textContent = value.summary; $("#storyboard-batch-jobs").replaceChildren(...value.jobs.map(job => { const item = document.createElement("li"); item.dataset.state = job.state; item.textContent = `Shot ${job.order} · ${job.state} · ${job.prompt}`; return item; })); $("#advance-storyboard-batch").disabled = !value.canAdvance; $("#cancel-storyboard-batch").disabled = !value.canCancel; $("#retry-storyboard-batch").disabled = !value.canRetry; }
async function reloadStoryboardBatch() { if (storyboardBatch) storyboardBatch = await api(`/api/v1/projects/${projectId}/storyboard-batches/${storyboardBatch.id}`); renderStoryboardBatch(); await refresh(); }
$("#start-storyboard-batch").onclick = async () => { storyboardBatch = await api(`/api/v1/projects/${projectId}/storyboard-batches`, json("POST", { sessionId, idempotencyKey: crypto.randomUUID() })); renderStoryboardBatch(); await refresh(); };
$("#advance-storyboard-batch").onclick = async () => { storyboardBatch = await api(`/api/v1/projects/${projectId}/storyboard-batches/${storyboardBatch.id}/tick`, json("POST", {})); renderStoryboardBatch(); await refresh(); };
$("#cancel-storyboard-batch").onclick = async () => { const job = activeStoryboardJob(storyboardBatch); if (job) await api(`/api/v1/jobs/${job.id}/cancel`, json("POST", {})); await reloadStoryboardBatch(); };
$("#retry-storyboard-batch").onclick = async () => { const job = retryableStoryboardJob(storyboardBatch); if (job) await api(`/api/v1/jobs/${job.id}/retry`, json("POST", { idempotencyKey: crypto.randomUUID() })); await reloadStoryboardBatch(); };
$("#export-edl").onclick = async () => { const value = await api(`/api/v1/projects/${projectId}/exports/manifest`); $("#export-download").href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)])); $("#export-download").hidden = false; };
$("#render-export").onclick = async () => { const selection = reviewedExportSelection({ format: $("#render-format").value, quality: $("#render-quality").value, reviewed: $("#render-reviewed").checked }); $("#workflow-state").textContent = "Loading: rendering local MP4 preview…"; const result = await api(`/api/v1/projects/${projectId}/exports/render`, json("POST", selection)); $("#render-download").href = result.asset.downloadUrl; $("#render-download").download = result.asset.filename; $("#render-download").hidden = false; $("#workflow-state").textContent = exportSuccessMessage(result); };
async function bootstrap() { $("#workflow-state").textContent = "Loading: recovering workspace…"; models = await api("/api/v1/models"); const projects = await api("/api/v1/projects"); const project = projects.find(p => p.status === "active") || await api("/api/v1/projects", json("POST", { name: "Local demo" })); projectId = project.id; snapshot = await api(`/api/v1/projects/${projectId}`); const session = snapshot.sessions.find(s => s.status === "active") || await api(`/api/v1/projects/${projectId}/sessions`, json("POST", { name: "Main canvas" })); sessionId = session.id; storyboardBatch = (await api(`/api/v1/projects/${projectId}/storyboard-batches`))[0] || null; $("#project-name").textContent = `/ ${project.name}`; renderStoryboardBatch(); await refresh(); await refreshLibrary(); $("#workflow-state").textContent = `Ready: ${models.filter(model => model.adapterId === "ark").length} Ark models available.`; }
function showAuth(mode = "login", message = "") { $("#auth-shell").hidden = false; $("#workspace-shell").hidden = true; $("#login-form").hidden = mode !== "login"; $("#register-form").hidden = mode !== "register"; $("#show-login").classList.toggle("active", mode === "login"); $("#show-register").classList.toggle("active", mode === "register"); $("#auth-state").textContent = message || (mode === "login" ? "Sign in to continue." : "Create an account to start a workspace."); }
async function showWorkspace() { $("#auth-shell").hidden = true; $("#workspace-shell").hidden = false; if (!workspaceStarted) { workspaceStarted = true; try { await bootstrap(); } catch (error) { workspaceStarted = false; throw error; } } }
async function establishSession(email, password) { const value = await api("/api/v1/auth/login", json("POST", { email, password })); csrfToken = value.csrfToken; await showWorkspace(); }
$("#show-login").onclick = () => showAuth("login");
$("#show-register").onclick = () => showAuth("register");
$("#login-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await establishSession($("#login-email").value, $("#login-password").value); } catch (error) { showAuth("login", error.message); } finally { button.disabled = false; } });
$("#register-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter, email = $("#register-email").value, password = $("#register-password").value; button.disabled = true; try { await api("/api/v1/auth/register", json("POST", { email, password })); await establishSession(email, password); } catch (error) { showAuth("register", error.message); } finally { button.disabled = false; } });
$("#logout").onclick = async () => { try { await api("/api/v1/auth/logout", json("POST", {})); } finally { csrfToken = ""; workspaceStarted = false; projectId = sessionId = undefined; showAuth("login", "Signed out."); } };
async function bootstrapAuth() { try { await api("/api/v1/auth/me"); csrfToken = (await api("/api/v1/auth/csrf")).csrfToken; await showWorkspace(); } catch { showAuth("login"); } }
async function api(path, options = {}) { const method = options.method || "GET", headers = { "content-type": "application/json", ...(options.headers || {}) }; if (!new Set(["GET", "HEAD", "OPTIONS"]).has(method) && csrfToken) headers["x-csrf-token"] = csrfToken; const response = await fetch(path, { ...options, headers }); const value = await response.json(); if (!response.ok) { const error = new Error(value.error?.message || "Request failed"); error.code = value.error?.code; error.status = response.status; error.details = value.error?.details; throw error; } return value; }
const json = (method, body) => ({ method, body: JSON.stringify(body) }); const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[char]); const showError = error => { const conflict = collaborationConflictView(error); if (conflict) { $("#collaboration-conflict-title").textContent = conflict.title; $("#collaboration-conflict-message").textContent = conflict.message; $("#reload-collaboration").textContent = conflict.action; $("#collaboration-conflict").hidden = false; } $("#workflow-state").textContent = `Error: ${error.code ? `${error.code}: ` : ""}${error.message}`; };
bootstrapAuth().catch(showError);
