import { NODE_TYPES } from "./model.js";
import { TUTORIALS, tutorialById } from "./tutorials.js";

const icons = { text: "T", image: "▧", video: "▶", audio: "♪", script: "≡" };
let snapshot = { nodes: [], edges: [], groups: [] }, models = [], selected = [], selectedGraph = null, view = { x: 0, y: 0, scale: 1 }, projectId, sessionId, csrfToken = "", workspaceStarted = false;
const $ = selector => document.querySelector(selector), viewport = $("#viewport"), canvas = $("#canvas"), nodeForm = $("#node-form"), graphForm = $("#graph-form");

$("#node-tools").replaceChildren(...NODE_TYPES.map(type => button(type, async () => {
  const rect = viewport.getBoundingClientRect(), position = { x: (rect.width / 2 - view.x) / view.scale - 120, y: (rect.height / 2 - view.y) / view.scale - 70 };
  const node = await api(`/api/v1/sessions/${sessionId}/nodes`, json("POST", { type, position })); await refresh(node.id);
})));

function button(label, action) { const element = document.createElement("button"); element.className = "tool"; element.innerHTML = `<span>${icons[label] || "+"}</span>${label}`; element.addEventListener("click", () => action().catch(showError)); return element; }
async function refresh(selectId) { snapshot = await api(`/api/v1/projects/${projectId}`); if (selectId) selected = [selectId]; render(); }
function render() {
  canvas.style.transform = `translate(${view.x}px, ${view.y}px) scale(${view.scale})`;
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.classList.add("edges");
  for (const edge of snapshot.edges) { const from = snapshot.nodes.find(n => n.id === edge.fromNodeId), to = snapshot.nodes.find(n => n.id === edge.toNodeId); if (!from || !to) continue; const line = document.createElementNS(svg.namespaceURI, "line"); line.setAttribute("x1", from.position.x + 120); line.setAttribute("y1", from.position.y + 60); line.setAttribute("x2", to.position.x + 120); line.setAttribute("y2", to.position.y + 60); line.dataset.edgeId = edge.id; line.addEventListener("click", event => { event.stopPropagation(); selectedGraph = { kind: "edge", value: edge }; selected = []; render(); }); svg.append(line); }
  canvas.replaceChildren(...snapshot.groups.map(renderGroup), svg, ...snapshot.nodes.map(renderNode));
  const node = snapshot.nodes.find(item => item.id === selected.at(-1));
  $("#inspector-empty").hidden = Boolean(node || selectedGraph); nodeForm.hidden = !node; graphForm.hidden = !selectedGraph;
  if (node) { $("#node-title").value = node.title; $("#node-content").value = node.content; $("#node-meta").textContent = `${node.type} · ${Math.round(node.position.x)}, ${Math.round(node.position.y)} · ${node.status} · v${node.version}`; $("#generation-panel").hidden = !["image", "video", "audio"].includes(node.type); if (!$("#generation-panel").hidden) renderParameters(node.type); $("#node-history").replaceChildren(...node.runs.map(run => { const li = document.createElement("li"); li.textContent = `${run.state} · ${run.events.length} events · ${run.error?.code || run.assetId || "pending"}`; return li; }), ...node.resultVersions.map(result => { const li = document.createElement("li"); const link = document.createElement("a"); link.href = result.downloadUrl; link.textContent = `result ${result.id}`; li.append(link); return li; })); }
  if (selectedGraph) { $("#graph-title").value = selectedGraph.value.title || ""; $("#graph-meta").textContent = `${selectedGraph.kind} · v${selectedGraph.value.version}`; }
  $("#zoom-label").value = `${Math.round(view.scale * 100)}%`;
}
function renderNode(node) { const element = document.createElement("article"); element.className = `node node-${node.type}${selected.includes(node.id) ? " selected" : ""}`; element.dataset.nodeId = node.id; element.style.transform = `translate(${node.position.x}px, ${node.position.y}px)`; element.innerHTML = `<header><span>${icons[node.type]}</span><strong>${escapeHtml(node.title)}</strong><small>${node.type}</small></header><p>${escapeHtml(node.content)}</p><footer data-state="${node.status}"><i></i>${node.status}</footer>`; element.addEventListener("click", event => { event.stopPropagation(); selectedGraph = null; selected = event.shiftKey ? [...new Set([...selected, node.id])] : [node.id]; render(); }); element.addEventListener("pointerdown", event => dragNode(event, node)); return element; }
function renderGroup(group) { const members = snapshot.nodes.filter(node => group.nodeIds.includes(node.id)); const element = document.createElement("section"); element.className = "graph-group"; element.dataset.groupId = group.id; const minX = Math.min(...members.map(n => n.position.x)) - 24, minY = Math.min(...members.map(n => n.position.y)) - 44, maxX = Math.max(...members.map(n => n.position.x + 240)) + 24, maxY = Math.max(...members.map(n => n.position.y + 120)) + 24; Object.assign(element.style, { transform: `translate(${minX}px, ${minY}px)`, width: `${maxX-minX}px`, height: `${maxY-minY}px` }); element.textContent = group.title; element.addEventListener("click", event => { event.stopPropagation(); selectedGraph = { kind: "group", value: group }; selected = []; render(); }); return element; }
function dragNode(event, node) { if (event.button !== 0) return; const start = { clientX: event.clientX, clientY: event.clientY, ...node.position }; const move = next => { node.position = { x: start.x + (next.clientX-start.clientX)/view.scale, y: start.y + (next.clientY-start.clientY)/view.scale }; render(); }; const end = async () => { window.removeEventListener("pointermove", move); await api(`/api/v1/nodes/${node.id}`, json("PATCH", { position: node.position, version: node.version })); await refresh(node.id); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }

$("#create-edge").addEventListener("click", async () => { if (selected.length !== 2) return showError(new Error("Select exactly two nodes (Shift-click)")); await api(`/api/v1/projects/${projectId}/edges`, json("POST", { fromNodeId: selected[0], toNodeId: selected[1] })); await refresh(); });
$("#create-group").addEventListener("click", async () => { if (selected.length < 1) return showError(new Error("Select one or more nodes")); await api(`/api/v1/projects/${projectId}/groups`, json("POST", { title: "New group", nodeIds: selected })); await refresh(); });
nodeForm.addEventListener("change", async () => { const node = snapshot.nodes.find(item => item.id === selected.at(-1)); if (!node) return; await api(`/api/v1/nodes/${node.id}`, json("PATCH", { title: $("#node-title").value, content: $("#node-content").value, version: node.version })); await refresh(node.id); });
graphForm.addEventListener("change", async () => { const graph = selectedGraph; await api(`/api/v1/${graph.kind}s/${graph.value.id}`, json("PATCH", { title: $("#graph-title").value, version: graph.value.version })); snapshot = await api(`/api/v1/projects/${projectId}`); selectedGraph = { kind: graph.kind, value: snapshot[`${graph.kind}s`].find(item => item.id === graph.value.id) }; render(); });

viewport.addEventListener("pointerdown", event => { if (event.target !== viewport && event.target !== canvas) return; selected = []; selectedGraph = null; const start = { clientX: event.clientX, clientY: event.clientY, ...view }; const move = next => { view.x = start.x + next.clientX-start.clientX; view.y = start.y + next.clientY-start.clientY; render(); }; const end = () => window.removeEventListener("pointermove", move); window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); render(); });
viewport.addEventListener("wheel", event => { event.preventDefault(); setScale(view.scale * (event.deltaY < 0 ? 1.1 : .9)); }, { passive: false });
$("#zoom-in").onclick = () => setScale(view.scale + .1); $("#zoom-out").onclick = () => setScale(view.scale - .1); function setScale(scale) { view.scale = Math.min(2, Math.max(.4, scale)); render(); }
$("#rename-project").onclick = async () => { const name = prompt("Project name", snapshot.project.name); if (name) { await api(`/api/v1/projects/${projectId}`, json("PATCH", { name, version: snapshot.project.version })); await refresh(); } };
$("#archive-project").onclick = async () => { await api(`/api/v1/projects/${projectId}`, json("PATCH", { status: "archived", version: snapshot.project.version })); await refresh(); };
$("#api-access").onclick = async () => { $("#api-access-dialog").showModal(); await refreshKeyApplications(); };
$("#tutorials").onclick = () => { renderTutorialList(); $("#tutorial-dialog").showModal(); };
function renderTutorialList() {
  $("#tutorial-detail").hidden = true; $("#tutorial-list").hidden = false;
  $("#tutorial-list").replaceChildren(...TUTORIALS.map(tutorial => {
    const card = document.createElement("button"); card.type = "button"; card.className = "tutorial-card";
    card.innerHTML = `<span>${escapeHtml(tutorial.category)} · ${escapeHtml(tutorial.level)}</span><strong>${escapeHtml(tutorial.title)}</strong><small>${escapeHtml(tutorial.duration)} · ${escapeHtml(tutorial.calls)}</small><p>${escapeHtml(tutorial.outcome)}</p>`;
    card.onclick = () => renderTutorial(tutorial.id); return card;
  }));
}
function renderTutorial(id) {
  const tutorial = tutorialById(id), detail = $("#tutorial-detail"); $("#tutorial-list").hidden = true; detail.hidden = false;
  detail.innerHTML = `<button class="tutorial-back" type="button">← 全部教程</button><p class="eyebrow">${escapeHtml(tutorial.category)} · ${escapeHtml(tutorial.level)}</p><h2>${escapeHtml(tutorial.title)}</h2><p class="tutorial-outcome">${escapeHtml(tutorial.outcome)}</p><div class="tutorial-meta"><span>${escapeHtml(tutorial.duration)}</span><span>${escapeHtml(tutorial.calls)}</span><span>${tutorial.nodes.length} 个节点</span></div><h3>操作步骤</h3><ol>${tutorial.steps.map(step => `<li>${escapeHtml(step)}</li>`).join("")}</ol><h3>验收清单</h3><ul>${tutorial.checks.map(check => `<li>${escapeHtml(check)}</li>`).join("")}</ul><p class="tutorial-safety">开始教程只会创建并连接节点，不会提交模型任务或产生费用。请在生成前检查模型、参数和管理员额度。</p><button class="tutorial-start" type="button">把教程蓝图放到当前画布</button>`;
  detail.querySelector(".tutorial-back").onclick = renderTutorialList;
  detail.querySelector(".tutorial-start").onclick = event => startTutorial(tutorial, event.currentTarget).catch(showError);
}
async function startTutorial(tutorial, trigger) {
  trigger.disabled = true;
  try {
    const created = [];
    for (const spec of tutorial.nodes) {
      const node = await api(`/api/v1/sessions/${sessionId}/nodes`, json("POST", { type: spec.type, position: { x: spec.x, y: spec.y } }));
      created.push(await api(`/api/v1/nodes/${node.id}`, json("PATCH", { title: spec.title, content: spec.content, version: node.version })));
    }
    for (let index = 1; index < created.length; index += 1) await api(`/api/v1/projects/${projectId}/edges`, json("POST", { fromNodeId: created[index - 1].id, toNodeId: created[index].id }));
    await api(`/api/v1/projects/${projectId}/groups`, json("POST", { title: `Tutorial · ${tutorial.title}`, nodeIds: created.map(node => node.id) }));
    await refresh(created[0].id); $("#tutorial-dialog").close(); $("#workflow-state").textContent = `Tutorial ready: ${tutorial.title}. Review each prompt before generating.`;
  } finally { trigger.disabled = false; }
}
$("#key-application-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await api("/api/v1/key-applications", json("POST", { reason: $("#key-application-reason").value, requestedLimitUnits: Math.round(Number($("#key-application-limit").value) * 10000), currency: "USD", unitScale: 10000 })); event.target.reset(); await refreshKeyApplications(); } catch (error) { $("#key-application-state").textContent = `Error: ${error.message}`; } finally { button.disabled = false; } });
$("#create-api-key").onclick = async () => { const issued = await api("/api/v1/api-keys", json("POST", { name: "primary" })); $("#issued-key").textContent = `Copy now — this external API key will not be shown again: ${issued.key}`; await refreshKeyApplications(); };
async function refreshKeyApplications() { const [applications, keys] = await Promise.all([api("/api/v1/key-applications"), api("/api/v1/api-keys")]); $("#key-application-state").textContent = applications.length ? "Your application history" : "No application submitted yet."; $("#key-application-list").replaceChildren(...[...applications].reverse().map(item => { const li = document.createElement("li"); li.textContent = `${item.status} · limit ${money(item.requestedLimitUnits ?? item.requestedLimitMicros, item.currency, item.unitScale)} · ${item.reason}${item.reviewNote ? ` · ${item.reviewNote}` : ""}`; return li; })); const approved = applications.some(item => item.status === "approved"); $("#key-issue-panel").hidden = !approved; $("#api-key-list").replaceChildren(...keys.map(key => { const li = document.createElement("li"); li.textContent = `${key.name} · ${key.prefix}… · ${key.status}`; return li; })); }
function money(units, currency = "CNY", scale = 1_000_000) { return new Intl.NumberFormat("en-US", { style: "currency", currency, minimumFractionDigits: 4, maximumFractionDigits: 4 }).format(Number(units || 0) / scale); }
$("#generate").onclick = async () => { const node = snapshot.nodes.find(item => item.id === selected.at(-1)), chosen = models.find(x => x.id === $("#generation-model").value), value = id => $(id).value || undefined, parameters = { mode: value("#generation-mode"), aspect: value("#generation-aspect"), resolution: value("#generation-resolution"), duration: value("#generation-duration") ? Number(value("#generation-duration")) : undefined, audio: chosen.schema.audio === undefined ? undefined : $("#generation-audio").checked }; let job; if (chosen.adapterId === "ark") { job = await api(`/api/v1/sessions/${sessionId}/ark-jobs`, json("POST", { nodeId: node.id, prompt: $("#generation-prompt").value, model: chosen.id, capability: node.type, parameters, idempotencyKey: crypto.randomUUID() })); while (!["succeeded","failed"].includes(job.state)) { await new Promise(resolve => setTimeout(resolve, 1000)); job = await api(`/api/v1/jobs/${job.id}/ark-poll`, json("POST", {})); } } else { job = await api(`/api/v1/sessions/${sessionId}/jobs`, json("POST", { nodeId: node.id, prompt: $("#generation-prompt").value, adapterId: chosen.adapterId, ...parameters, outcome: $("#simulate-failure").checked ? "failed" : "succeeded" })); while (!["succeeded","failed","canceled"].includes(job.state)) job = await api(`/api/v1/jobs/${job.id}/tick`, json("POST", {})); } await refresh(node.id); await refreshLibrary(); };
function options(select, values = []) { select.replaceChildren(...values.map(value => { const option = document.createElement("option"); option.value = value; option.textContent = value; return option; })); select.closest("label").hidden = !values.length; }
function renderParameters(kind) { const available = models.filter(x => x.kind === kind), current = available.find(x => x.id === $("#generation-model").value) || available[0]; options($("#generation-model"), available.map(x => x.id)); if (!current) return; $("#generation-model").value = current.id; for (const [field, values] of [["mode", current.schema.modes], ["aspect", current.schema.aspects], ["resolution", current.schema.resolutions], ["duration", current.schema.durations]]) options($(`#generation-${field}`), values); $("#generation-audio").checked = current.schema.audio === true; $("#generation-audio").disabled = current.schema.audio === undefined; $("#reference-limit").textContent = `Up to ${current.schema.maxReferences} references`; }
$("#generation-model").onchange = () => renderParameters(snapshot.nodes.find(x => x.id === selected.at(-1)).type);
async function refreshLibrary() { const query = new URLSearchParams({ search: $("#library-search").value, kind: $("#library-kind").value }), [assets, history] = await Promise.all([api(`/api/v1/projects/${projectId}/assets?${query}`), api(`/api/v1/projects/${projectId}/history?${query}`)]); $("#asset-library").replaceChildren(...assets.map(asset => { const li = document.createElement("li"); li.textContent = `${asset.kind} · ${asset.filename} · ${asset.metadata?.provenance?.operation || asset.role}`; return li; }), ...history.map(run => { const li = document.createElement("li"); li.textContent = `run · ${run.kind} · ${run.state} · ${run.prompt}`; return li; })); }
$("#library-refresh").onclick = () => refreshLibrary().catch(showError);
$("#build-story").onclick = async () => { const story = await api(`/api/v1/projects/${projectId}/story`, json("PUT", { title: "Local demo", scenes: [{ title: "Opening" }] })); await api(`/api/v1/projects/${projectId}/storyboard`, json("PUT", { shots: [{ sceneId: story.scenes[0].id, prompt: "Opening", duration: 1 }] })); $("#workflow-state").textContent = "Success: story and shot persisted."; };
$("#export-edl").onclick = async () => { const value = await api(`/api/v1/projects/${projectId}/exports/manifest`); $("#export-download").href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)])); $("#export-download").hidden = false; };
async function bootstrap() { $("#workflow-state").textContent = "Loading: recovering local workspace…"; models = await api("/api/v1/models"); const projects = await api("/api/v1/projects"); const project = projects.find(p => p.status === "active") || await api("/api/v1/projects", json("POST", { name: "Local demo" })); projectId = project.id; snapshot = await api(`/api/v1/projects/${projectId}`); const session = snapshot.sessions.find(s => s.status === "active") || await api(`/api/v1/projects/${projectId}/sessions`, json("POST", { name: "Main canvas" })); sessionId = session.id; $("#project-name").textContent = `/ ${project.name}`; await refresh(); await refreshLibrary(); }
function showAuth(mode = "login", message = "") { $("#auth-shell").hidden = false; $("#workspace-shell").hidden = true; $("#login-form").hidden = mode !== "login"; $("#register-form").hidden = mode !== "register"; $("#show-login").classList.toggle("active", mode === "login"); $("#show-register").classList.toggle("active", mode === "register"); $("#auth-state").textContent = message || (mode === "login" ? "Sign in to continue." : "Create an account to start a workspace."); }
async function showWorkspace() { $("#auth-shell").hidden = true; $("#workspace-shell").hidden = false; if (!workspaceStarted) { workspaceStarted = true; await bootstrap(); } }
async function establishSession(email, password) { const value = await api("/api/v1/auth/login", json("POST", { email, password })); csrfToken = value.csrfToken; await showWorkspace(); }
$("#show-login").onclick = () => showAuth("login");
$("#show-register").onclick = () => showAuth("register");
$("#login-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await establishSession($("#login-email").value, $("#login-password").value); } catch (error) { showAuth("login", error.message); } finally { button.disabled = false; } });
$("#register-form").addEventListener("submit", async event => { event.preventDefault(); const button = event.submitter, email = $("#register-email").value, password = $("#register-password").value; button.disabled = true; try { await api("/api/v1/auth/register", json("POST", { email, password })); await establishSession(email, password); } catch (error) { showAuth("register", error.message); } finally { button.disabled = false; } });
$("#logout").onclick = async () => { try { await api("/api/v1/auth/logout", json("POST", {})); } finally { csrfToken = ""; workspaceStarted = false; projectId = sessionId = undefined; showAuth("login", "Signed out."); } };
async function bootstrapAuth() { try { await api("/api/v1/auth/me"); csrfToken = (await api("/api/v1/auth/csrf")).csrfToken; await showWorkspace(); } catch { showAuth("login"); } }
async function api(path, options = {}) { const method = options.method || "GET", headers = { "content-type": "application/json", ...(options.headers || {}) }; if (!new Set(["GET", "HEAD", "OPTIONS"]).has(method) && csrfToken) headers["x-csrf-token"] = csrfToken; const response = await fetch(path, { ...options, headers }); const value = await response.json(); if (!response.ok) { const error = new Error(value.error?.message || "Request failed"); error.code = value.error?.code; error.status = response.status; throw error; } return value; }
const json = (method, body) => ({ method, body: JSON.stringify(body) }); const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[char]); const showError = error => { $("#workflow-state").textContent = `Error: ${error.code ? `${error.code}: ` : ""}${error.message}`; };
bootstrapAuth().catch(showError);
