import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { AdapterGateError, createAdapterRegistry, localAdapter, optionalProviderAdapter } from "./adapters.js";
import { renderTimelineVideo } from "./render.js";

export const SCHEMA_VERSION = 3;
export const JOB_STATES = Object.freeze(["queued", "running", "succeeded", "failed", "canceled"]);
const TERMINAL = new Set(["succeeded", "failed", "canceled"]);
const TRANSITIONS = { queued: new Set(["running", "canceled"]), running: new Set(["succeeded", "failed", "canceled"]), succeeded: new Set(), failed: new Set(), canceled: new Set() };
export const ASSET_POLICY = Object.freeze({
  "image/png": { kind: "image", maxBytes: 8 * 1024 * 1024, extension: "png" },
  "image/jpeg": { kind: "image", maxBytes: 8 * 1024 * 1024, extension: "jpg" },
  "image/webp": { kind: "image", maxBytes: 8 * 1024 * 1024, extension: "webp" },
  "video/mp4": { kind: "video", maxBytes: 32 * 1024 * 1024, extension: "mp4" },
  "video/webm": { kind: "video", maxBytes: 32 * 1024 * 1024, extension: "webm" },
  "audio/mpeg": { kind: "audio", maxBytes: 16 * 1024 * 1024, extension: "mp3" },
  "audio/wav": { kind: "audio", maxBytes: 16 * 1024 * 1024, extension: "wav" }
});

export class DomainError extends Error {
  constructor(code, message, status = 400, details) { super(message); this.name = "DomainError"; this.code = code; this.status = status; this.details = details; }
}
const required = (v, name) => { if (typeof v !== "string" || !v.trim()) throw new DomainError("INVALID_INPUT", `${name} is required`); return v.trim(); };
const clone = (v) => structuredClone(v);

export function createMemoryStore(options = {}) { return createStore(options); }
export function createPersistentStore(file, options = {}) { return createStore({ ...options, file }); }
export function createDatabaseStore(backend, options = {}) { return createStore({ ...options, backend }); }

function createStore({ file = null, backend = null, id = () => crypto.randomUUID(), now = () => new Date().toISOString(), adapters = [localAdapter, optionalProviderAdapter({ id: "optional-video", provider: "optional", execute: request => ({ adapterId: "optional-video", kind: request.kind }) })] } = {}) {
  let loaded = backend ? backend.read() : { state: load(file), revision: 0 }, state = loaded.state, revision = loaded.revision;
  const adapterRegistry = createAdapterRegistry(adapters);
  const maps = () => ({ projects: new Map(state.projects.map(x => [x.id, x])), sessions: new Map(state.sessions.map(x => [x.id, x])), nodes: new Map(state.nodes.map(x => [x.id, x])), edges: new Map(state.edges.map(x => [x.id, x])), groups: new Map(state.groups.map(x => [x.id, x])), jobs: new Map(state.jobs.map(x => [x.id, x])), assets: new Map(state.assets.map(x => [x.id, x])), users: new Map(state.users.map(x => [x.id, x])) });
  let db = maps(), pendingAssets = [];
  const persist = () => { if (backend) { revision = backend.commit(state, revision); return; } if (!file) return; mkdirSync(dirname(file), { recursive: true }); const temp = `${file}.tmp`; writeFileSync(temp, JSON.stringify(state)); renameSync(temp, file); };
  const sync = () => { state = { schemaVersion: SCHEMA_VERSION, projects: [...db.projects.values()], sessions: [...db.sessions.values()], nodes: [...db.nodes.values()], edges: [...db.edges.values()], groups: [...db.groups.values()], jobs: [...db.jobs.values()], assets: [...db.assets.values()], users: [...db.users.values()] }; try { persist(); pendingAssets = []; } catch (error) { for (const asset of pendingAssets) backend?.assets.remove(asset); pendingAssets = []; if (backend) { loaded = backend.read(); state = loaded.state; revision = loaded.revision; db = maps(); } throw error; } };
  const get = (map, rid, kind) => { const record = map.get(rid); if (!record) throw new DomainError("NOT_FOUND", `${kind} not found`, 404); return record; };
  const actor = (actorId = "local-owner") => { if (actorId === "local-owner" && !db.users.has(actorId)) db.users.set(actorId, { id: actorId, name: "Local owner", createdAt: now() }); return get(db.users, actorId, "user"); };
  const roleFor = (project, actorId) => project.members.find(m => m.userId === actorId)?.role;
  const authorize = (project, actorId, allowed) => { actor(actorId); const role = roleFor(project, actorId); if (!allowed.includes(role)) throw new DomainError("FORBIDDEN", "project role does not allow this operation", 403, { required: allowed, actual: role ?? null }); return role; };
  const touch = (record) => { record.version = (record.version || 0) + 1; record.updatedAt = now(); };
  const expect = (record, version) => { if (version !== undefined && Number(version) !== record.version) throw new DomainError("VERSION_CONFLICT", "record version is stale", 409, { expected: record.version, received: Number(version) }); };

  function createUser(input = {}) { const user = { id: input.id || id(), name: required(input.name, "name"), createdAt: now() }; if (db.users.has(user.id)) throw new DomainError("CONFLICT", "user already exists", 409); db.users.set(user.id, user); sync(); return clone(user); }
  function createProject(input = {}, actorId = "local-owner") { const user = actor(actorId); const project = { id: id(), name: required(input.name, "name"), status: "active", version: 1, createdAt: now(), updatedAt: now(), members: [{ userId: user.id, role: "owner" }], sessionIds: [], nodeIds: [], edgeIds: [], groupIds: [], assetIds: [], sceneIds: [], shotIds: [], timeline: { version: 1, tracks: [] } }; db.projects.set(project.id, project); sync(); return clone(project); }
  function listProjects(actorId = "local-owner", query = {}) { actor(actorId); return [...db.projects.values()].filter(p => roleFor(p, actorId) && (!query.status || p.status === query.status) && (!query.search || p.name.toLowerCase().includes(query.search.toLowerCase()))).map(clone); }
  function updateProject(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(p, input.version); if (input.name !== undefined) p.name = required(input.name, "name"); if (input.status !== undefined) { if (!new Set(["active", "archived"]).has(input.status)) throw new DomainError("INVALID_INPUT", "status must be active or archived"); p.status = input.status; } touch(p); sync(); return clone(p); }
  function addMember(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner"]); get(db.users, required(input.userId, "userId"), "user"); if (!new Set(["owner", "editor", "viewer"]).has(input.role)) throw new DomainError("INVALID_INPUT", "invalid role"); const old = p.members.find(m => m.userId === input.userId); if (old) old.role = input.role; else p.members.push({ userId: input.userId, role: input.role }); touch(p); sync(); return clone(p.members); }
  function createSession(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); const s = { id: id(), projectId, name: required(input.name, "name"), status: "active", version: 1, createdAt: now(), updatedAt: now(), closedAt: null, nodeIds: [] }; db.sessions.set(s.id, s); p.sessionIds.push(s.id); touch(p); sync(); return clone(s); }
  function assertScope(projectId, sessionId, actorId, allowed = ["owner", "editor", "viewer"]) { const p = get(db.projects, projectId, "project"); authorize(p, actorId, allowed); const s = get(db.sessions, sessionId, "session"); if (s.projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "session does not belong to project", 404); return { project: p, session: s }; }
  function closeSession(sessionId, input = {}, actorId = "local-owner") { const s = get(db.sessions, sessionId, "session"), p = get(db.projects, s.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(s, input.version); if (s.status === "closed") throw new DomainError("SESSION_CLOSED", "session is already closed", 409); s.status = "closed"; s.closedAt = now(); touch(s); sync(); return clone(s); }
  function createNode(sessionId, input = {}, actorId = "local-owner") { const s = get(db.sessions, sessionId, "session"), p = get(db.projects, s.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (s.status !== "active") throw new DomainError("SESSION_CLOSED", "cannot add a node to a closed session", 409); const type = required(input.type, "type"); if (!new Set(["text", "image", "video", "audio", "script"]).has(type)) throw new DomainError("INVALID_INPUT", `unsupported node type: ${type}`); const position = input.position || { x: 0, y: 0 }; if (![position.x, position.y].every(Number.isFinite)) throw new DomainError("INVALID_INPUT", "node position must be finite"); const n = { id: id(), projectId: p.id, sessionId, type, title: input.title?.trim() || type, content: input.content?.trim() || "", position: { x: position.x, y: position.y }, status: "draft", assetId: null, resultVersion: 0, runIds: [], version: 1, createdAt: now(), updatedAt: now() }; db.nodes.set(n.id, n); s.nodeIds.push(n.id); p.nodeIds.push(n.id); touch(s); touch(p); sync(); return clone(n); }
  function updateNode(nodeId, input = {}, actorId = "local-owner") { const n = get(db.nodes, nodeId, "node"), p = get(db.projects, n.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(n, input.version); for (const key of ["title", "content"]) if (input[key] !== undefined) n[key] = String(input[key]); if (input.position !== undefined) { if (![input.position.x, input.position.y].every(Number.isFinite)) throw new DomainError("INVALID_INPUT", "node position must be finite"); n.position = { x: input.position.x, y: input.position.y }; } touch(n); sync(); return clone(n); }
  function createEdge(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); const from = get(db.nodes, required(input.fromNodeId, "fromNodeId"), "node"), to = get(db.nodes, required(input.toNodeId, "toNodeId"), "node"); if (from.projectId !== p.id || to.projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "edge nodes must belong to project", 404); if (from.id === to.id) throw new DomainError("INVALID_GRAPH", "self edges are not allowed", 422); if ([...db.edges.values()].some(e => e.projectId === p.id && e.fromNodeId === from.id && e.toNodeId === to.id)) throw new DomainError("CONFLICT", "edge already exists", 409); if (reaches(to.id, from.id, p.id, db.edges)) throw new DomainError("INVALID_GRAPH", "edge would create a cycle", 422); const edge = { id: id(), projectId: p.id, fromNodeId: from.id, toNodeId: to.id, output: input.output || "result", input: input.input || "reference", title: input.title || "", version: 1, createdAt: now(), updatedAt: now() }; db.edges.set(edge.id, edge); p.edgeIds.push(edge.id); touch(p); sync(); return clone(edge); }
  function updateEdge(edgeId, input = {}, actorId = "local-owner") { const edge = get(db.edges, edgeId, "edge"), p = get(db.projects, edge.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(edge, input.version); for (const key of ["title", "output", "input"]) if (input[key] !== undefined) edge[key] = String(input[key]); touch(edge); sync(); return clone(edge); }
  function createGroup(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); const nodeIds = [...new Set(input.nodeIds || [])]; if (!nodeIds.length) throw new DomainError("INVALID_INPUT", "group requires nodes"); for (const nid of nodeIds) if (get(db.nodes, nid, "node").projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "group node belongs to another project", 404); const group = { id: id(), projectId: p.id, title: required(input.title, "title"), nodeIds, createdAt: now(), version: 1 }; db.groups.set(group.id, group); p.groupIds.push(group.id); touch(p); sync(); return clone(group); }
  function updateGroup(groupId, input = {}, actorId = "local-owner") { const group = get(db.groups, groupId, "group"), p = get(db.projects, group.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(group, input.version); if (input.title !== undefined) group.title = required(input.title, "title"); if (input.nodeIds !== undefined) { if (!Array.isArray(input.nodeIds) || !input.nodeIds.length) throw new DomainError("INVALID_INPUT", "group requires nodes"); for (const nid of input.nodeIds) if (get(db.nodes, nid, "node").projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "group node belongs to another project", 404); group.nodeIds = [...new Set(input.nodeIds)]; } touch(group); sync(); return clone(group); }

  function makeAsset({ project, sessionId = null, jobId = null, nodeId = null, kind, role, mimeType, filename, bytes, metadata = {} }) { const assetId = id(), a = { id: assetId, projectId: project.id, sessionId, jobId, nodeId, kind, role, mimeType, filename, byteLength: bytes.length, ...(backend ? backend.assets.put(project.id, assetId, bytes) : { bytes: Buffer.from(bytes).toString("base64") }), metadata, createdAt: now() }; if (backend) pendingAssets.push(a); db.assets.set(a.id, a); project.assetIds.push(a.id); touch(project); return a; }
  function manifest(a) { const base = a.sessionId ? `/api/v1/projects/${a.projectId}/sessions/${a.sessionId}/assets/${a.id}` : `/api/v1/projects/${a.projectId}/assets/${a.id}`; const { bytes, ...meta } = a; const downloadUrl = `${base}/content`; return { ...clone(meta), url: downloadUrl, manifestUrl: `${base}/manifest`, downloadUrl }; }
  function uploadReference(projectId, sessionId, { mimeType, filename, bytes } = {}, actorId = "local-owner") { const { project, session } = assertScope(projectId, sessionId, actorId, ["owner", "editor"]); if (session.status !== "active") throw new DomainError("SESSION_CLOSED", "cannot upload to a closed session", 409); const policy = ASSET_POLICY[mimeType]; if (!policy) throw new DomainError("UNSUPPORTED_MEDIA_TYPE", "unsupported reference media type", 415, { allowed: Object.keys(ASSET_POLICY) }); if (!Buffer.isBuffer(bytes) || !bytes.length) throw new DomainError("EMPTY_ASSET", "asset body must not be empty"); if (bytes.length > policy.maxBytes) throw new DomainError("ASSET_TOO_LARGE", "asset exceeds byte limit", 413, { maxBytes: policy.maxBytes, actualBytes: bytes.length }); const a = makeAsset({ project, sessionId, kind: policy.kind, role: "reference", mimeType, filename: safeFilename(filename, `reference.${policy.extension}`), bytes }); sync(); return manifest(a); }
  function listAssets(projectId, query = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor", "viewer"]); return p.assetIds.map(aid => db.assets.get(aid)).filter(a => (!query.kind || a.kind === query.kind) && (!query.role || a.role === query.role) && (!query.search || a.filename.toLowerCase().includes(query.search.toLowerCase()))).map(manifest); }
  function listHistory(projectId, query = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor", "viewer"]); return [...db.jobs.values()].filter(j => j.projectId === p.id && (!query.state || j.state === query.state) && (!query.kind || j.kind === query.kind) && (!query.search || `${j.prompt} ${j.modelId}`.toLowerCase().includes(query.search.toLowerCase()))).map(j => ({ ...clone(j), result: j.assetId ? manifest(db.assets.get(j.assetId)) : null })); }
  function copyAsset(sourceProjectId, assetId, targetProjectId, actorId = "local-owner") { const source = assetForScope(sourceProjectId, assetId, actorId), target = get(db.projects, targetProjectId, "project"); authorize(target, actorId, ["owner", "editor"]); const copied = makeAsset({ project: target, kind: source.kind, role: "reference", mimeType: source.mimeType, filename: source.filename, bytes: backend ? backend.assets.read(source) : Buffer.from(source.bytes, "base64"), metadata: { ...clone(source.metadata), provenance: { operation: "copy", sourceProjectId, sourceAssetId: source.id, sourceJobId: source.jobId, copiedAt: now() } } }); sync(); return manifest(copied); }
  function assetForScope(projectId, assetId, actorId) { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor", "viewer"]); const a = get(db.assets, assetId, "asset"); if (a.projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "asset does not belong to project", 404); return a; }
  function assetManifest(projectId, sessionOrAssetId, maybeAssetId, actorId = "local-owner") { const assetId = maybeAssetId || sessionOrAssetId; const a = assetForScope(projectId, assetId, actorId); if (maybeAssetId && a.sessionId !== sessionOrAssetId) throw new DomainError("SCOPE_MISMATCH", "asset does not belong to session", 404); return manifest(a); }
  function assetContent(projectId, sessionOrAssetId, maybeAssetId, actorId = "local-owner") { const assetId = maybeAssetId || sessionOrAssetId; const a = assetForScope(projectId, assetId, actorId); if (maybeAssetId && a.sessionId !== sessionOrAssetId) throw new DomainError("SCOPE_MISMATCH", "asset does not belong to session", 404); return { manifest: manifest(a), bytes: backend ? backend.assets.read(a) : Buffer.from(a.bytes, "base64") }; }

  const providers = Object.freeze([
    { id: "local-image", provider: "local", kind: "image", capabilities: ["text-to-image", "image-reference"], deterministic: true },
    { id: "local-video", provider: "local", kind: "video", capabilities: ["text-to-video", "image-reference", "video-reference"], deterministic: true },
    { id: "local-audio", provider: "local", kind: "audio", capabilities: ["text-to-audio", "audio-reference"], deterministic: true }
  ]);
  function listModels() { return providers.map(model => ({ ...model, adapterId: "local-deterministic", schema: adapterRegistry.schema("local-deterministic").capabilities[model.kind] })); }
  function routeModel(kind, capability, requested) { const candidates = providers.filter(m => m.kind === kind && m.capabilities.includes(capability)); if (requested) { const exact = providers.find(m => m.id === requested); if (!exact || exact.kind !== kind || !exact.capabilities.includes(capability)) throw new DomainError("UNSUPPORTED_CAPABILITY", "requested model does not support capability", 422, { kind, capability, modelId: requested }); return exact; } if (!candidates.length) throw new DomainError("UNSUPPORTED_CAPABILITY", "no model supports capability", 422, { kind, capability }); return candidates[0]; }
  function createJob(sessionId, input = {}, actorId = "local-owner") { const s = get(db.sessions, sessionId, "session"), p = get(db.projects, s.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (s.status !== "active") throw new DomainError("SESSION_CLOSED", "cannot generate in a closed session", 409); const n = get(db.nodes, required(input.nodeId, "nodeId"), "node"); if (n.sessionId !== s.id) throw new DomainError("SCOPE_MISMATCH", "node does not belong to session", 404); if (!new Set(["image", "video", "audio"]).has(n.type)) throw new DomainError("INVALID_INPUT", "generation requires an image, video, or audio node"); const refs = input.referenceAssetIds ?? []; if (!Array.isArray(refs)) throw new DomainError("INVALID_INPUT", "referenceAssetIds must be an array"); for (const aid of refs) { const a = get(db.assets, aid, "asset"); if (a.projectId !== p.id || a.role !== "reference") throw new DomainError("SCOPE_MISMATCH", "reference asset does not belong to project", 404); } const prompt = required(input.prompt, "prompt"), adapterId = input.adapterId || "local-deterministic"; let adapterResult; try { adapterResult = adapterRegistry.execute(adapterId, { kind: n.type, prompt, referenceAssetIds: refs, mode: input.mode, aspect: input.aspect, resolution: input.resolution, duration: input.duration, audio: input.audio }, { credential: input.credential, approvedBudgetCents: input.approvedBudgetCents }); } catch (error) { if (error instanceof AdapterGateError) throw new DomainError(error.code, error.message, 422); throw error; } const parameters = Object.fromEntries(["mode", "aspect", "resolution", "duration", "audio"].filter(k => input[k] !== undefined).map(k => [k, input[k]])); const j = { id: id(), projectId: p.id, sessionId, nodeId: n.id, kind: n.type, capability: input.capability || `text-to-${n.type}`, modelId: adapterId, adapterId, provider: adapterRegistry.schema(adapterId).provider, adapterResult, parameters, prompt, referenceAssetIds: [...new Set(refs)], outcome: input.outcome === "failed" ? "failed" : "succeeded", state: "queued", assetId: null, error: null, createdAt: now(), updatedAt: now(), events: [] }; appendEvent(j, "queued", now); db.jobs.set(j.id, j); n.status = "queued"; n.runIds.push(j.id); touch(n); sync(); return clone(j); }
  function transitionJob(jobId, next, detail = {}, actorId = "local-owner") { const j = get(db.jobs, jobId, "job"); const n = get(db.nodes, j.nodeId, "node"), p = get(db.projects, j.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (!JOB_STATES.includes(next)) throw new DomainError("INVALID_STATE", `unknown job state: ${next}`); if (!TRANSITIONS[j.state].has(next)) throw new DomainError("INVALID_TRANSITION", `cannot transition ${j.state} to ${next}`, 409); j.state = next; j.updatedAt = now(); n.status = next; if (next === "failed") j.error = { code: detail.code || "GENERATION_FAILED", message: detail.message || "Local simulation failed" }; if (next === "succeeded") { const output = resultFixture(j); const a = makeAsset({ project: p, sessionId: j.sessionId, jobId: j.id, nodeId: n.id, kind: j.kind, role: "result", ...output, metadata: { modelId: j.modelId, prompt: j.prompt, referenceAssetIds: j.referenceAssetIds } }); j.assetId = a.id; n.assetId = a.id; n.content = manifest(a).downloadUrl; detail = { ...detail, assetId: a.id }; } touch(n); appendEvent(j, next, now, detail); sync(); return clone(j); }
  function tickJob(jobId, actorId = "local-owner") { const j = get(db.jobs, jobId, "job"), p = get(db.projects, j.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (TERMINAL.has(j.state)) return clone(j); return j.state === "queued" ? transitionJob(jobId, "running", {}, actorId) : transitionJob(jobId, j.outcome === "failed" ? "failed" : "succeeded", {}, actorId); }
  function createArkCanvasJob(sessionId, input = {}, arkJob, actorId = "local-owner") { const s = get(db.sessions, sessionId, "session"), p = get(db.projects, s.projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (s.status !== "active") throw new DomainError("SESSION_CLOSED", "cannot generate in a closed session", 409); const n = get(db.nodes, required(input.nodeId, "nodeId"), "node"); if (n.sessionId !== s.id || !new Set(["image", "video", "audio"]).has(n.type)) throw new DomainError("SCOPE_MISMATCH", "generation node does not belong to session", 404); const existing = [...db.jobs.values()].find(j => j.projectId === p.id && j.arkJobId === arkJob.id); if (existing) return clone(existing); const prompt = required(input.prompt, "prompt"), state = arkJob.status === "failed" ? "failed" : "running", j = { id: id(), projectId: p.id, sessionId, nodeId: n.id, kind: n.type, capability: arkJob.capability, modelId: arkJob.model, adapterId: "ark", provider: "volcengine-ark", parameters: structuredClone(input.parameters || {}), prompt, referenceAssetIds: [], outcome: "remote", state, arkJobId: arkJob.id, assetId: null, error: arkJob.error || null, createdAt: now(), updatedAt: now(), events: [] }; appendEvent(j, "queued", now); appendEvent(j, state, now, { arkJobId: arkJob.id }); db.jobs.set(j.id, j); n.status = state; n.runIds.push(j.id); touch(n); sync(); return clone(j); }
  function arkCanvasJob(jobId, actorId = "local-owner") { const j = get(db.jobs, jobId, "job"); authorize(get(db.projects, j.projectId, "project"), actorId, ["owner", "editor", "viewer"]); if (!j.arkJobId) throw new DomainError("INVALID_INPUT", "job is not an Ark canvas job", 400); return clone(j); }
  function reconcileArkCanvasJob(jobId, arkJob, output, actorId = "local-owner") { const j = get(db.jobs, jobId, "job"), p = get(db.projects, j.projectId, "project"), n = get(db.nodes, j.nodeId, "node"); authorize(p, actorId, ["owner", "editor"]); if (j.arkJobId !== arkJob.id) throw new DomainError("SCOPE_MISMATCH", "Ark job does not belong to canvas job", 404); if (TERMINAL.has(j.state)) return clone(j); if (arkJob.status === "failed") { j.state = n.status = "failed"; j.error = arkJob.error || { code: "ARK_PROVIDER_ERROR", message: "Ark generation failed" }; appendEvent(j, "failed", now, { arkJobId: arkJob.id }); touch(n); sync(); return clone(j); } if (arkJob.status !== "succeeded") return clone(j); if (!output?.bytes?.length || typeof output.mimeType !== "string") throw new DomainError("ARK_ASSET_REJECTED", "completed Ark job has no validated asset", 502); const extension = output.mimeType === "video/mp4" ? "mp4" : output.mimeType === "audio/wav" ? "wav" : output.mimeType === "image/png" ? "png" : "bin", a = makeAsset({ project: p, sessionId: j.sessionId, jobId: j.id, nodeId: n.id, kind: j.kind, role: "result", mimeType: output.mimeType, filename: `openreel-${j.id}.${extension}`, bytes: output.bytes, metadata: { modelId: j.modelId, prompt: j.prompt, arkJobId: arkJob.id, provider: "volcengine-ark" } }); j.state = n.status = "succeeded"; j.assetId = n.assetId = a.id; n.content = manifest(a).downloadUrl; appendEvent(j, "succeeded", now, { assetId: a.id, arkJobId: arkJob.id }); if (["video", "audio"].includes(j.kind)) { let track = p.timeline.tracks.find(t => t.kind === j.kind); if (!track) { track = { id: id(), kind: j.kind, clips: [] }; p.timeline.tracks.push(track); } const start = Math.max(0, ...p.timeline.tracks.flatMap(t => t.clips.map(c => c.start + c.outPoint - c.inPoint))); track.clips.push({ id: id(), assetId: a.id, order: track.clips.length, inPoint: 0, outPoint: Number(j.parameters.duration) || 5, start }); p.timeline.version += 1; p.timeline.updatedAt = now(); } touch(n); sync(); return clone(j); }
  function progress(jobId, afterSeq = 0, actorId = "local-owner") { const j = get(db.jobs, jobId, "job"), cursor = Number(afterSeq); authorize(get(db.projects, j.projectId, "project"), actorId, ["owner", "editor", "viewer"]); if (!Number.isInteger(cursor) || cursor < 0) throw new DomainError("INVALID_CURSOR", "afterSeq must be a non-negative integer"); return { jobId, state: j.state, events: clone(j.events.filter(e => e.seq > cursor)), nextSeq: j.events.at(-1)?.seq || cursor, terminal: TERMINAL.has(j.state) }; }

  function upsertStory(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); const scenes = input.scenes; if (!Array.isArray(scenes)) throw new DomainError("INVALID_INPUT", "scenes must be an array"); const existing = new Map((p.story?.scenes || []).map(s => [s.id, s])); p.story = { title: input.title || p.story?.title || p.name, synopsis: input.synopsis ?? p.story?.synopsis ?? "", version: (p.story?.version || 0) + 1, scenes: scenes.map((s, index) => ({ id: s.id || id(), title: required(s.title, `scenes[${index}].title`), summary: s.summary || "", order: index, version: (existing.get(s.id)?.version || 0) + 1 })) }; p.sceneIds = p.story.scenes.map(s => s.id); touch(p); sync(); return clone(p.story); }
  function upsertStoryboard(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); if (!p.story) throw new DomainError("INVALID_STATE", "story must exist before storyboard", 409); if (!Array.isArray(input.shots)) throw new DomainError("INVALID_INPUT", "shots must be an array"); const scenes = new Set(p.sceneIds); const shots = input.shots.map((s, index) => { if (!scenes.has(s.sceneId)) throw new DomainError("INVALID_INPUT", "shot sceneId is unknown"); for (const aid of s.referenceAssetIds || []) if (get(db.assets, aid, "asset").projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "shot reference belongs to another project", 404); return { id: s.id || id(), sceneId: s.sceneId, order: index, prompt: required(s.prompt, `shots[${index}].prompt`), duration: positive(s.duration, "duration"), referenceAssetIds: [...new Set(s.referenceAssetIds || [])], generatedAssetId: s.generatedAssetId || null }; }); p.storyboard = { version: (p.storyboard?.version || 0) + 1, shots }; p.shotIds = shots.map(s => s.id); touch(p); sync(); return clone(p.storyboard); }
  function upsertTimeline(projectId, input = {}, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); expect(p.timeline, input.version); if (!Array.isArray(input.tracks)) throw new DomainError("INVALID_INPUT", "tracks must be an array"); const tracks = input.tracks.map((t, ti) => ({ id: t.id || id(), kind: ["video", "audio"].includes(t.kind) ? t.kind : (() => { throw new DomainError("INVALID_INPUT", `tracks[${ti}].kind is invalid`); })(), clips: (t.clips || []).map((c, ci) => { const a = get(db.assets, c.assetId, "asset"); if (a.projectId !== p.id) throw new DomainError("SCOPE_MISMATCH", "clip asset belongs to another project", 404); const inPoint = nonnegative(c.inPoint ?? 0, "inPoint"), outPoint = positive(c.outPoint, "outPoint"); if (outPoint <= inPoint) throw new DomainError("INVALID_INPUT", "outPoint must exceed inPoint"); return { id: c.id || id(), assetId: a.id, order: ci, inPoint, outPoint, start: nonnegative(c.start ?? 0, "start") }; }) })); p.timeline = { version: p.timeline.version + 1, tracks, updatedAt: now() }; touch(p); sync(); return clone(p.timeline); }
  function exportManifest(projectId, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor", "viewer"]); const clips = p.timeline.tracks.flatMap(t => t.clips.map(c => ({ ...c, trackId: t.id, trackKind: t.kind }))); return { schema: "openreel-edl/v1", project: { id: p.id, name: p.name, version: p.version }, generatedAt: now(), preview: { duration: Math.max(0, ...clips.map(c => c.start + c.outPoint - c.inPoint)), clipCount: clips.length }, tracks: clone(p.timeline.tracks), assets: [...new Set(clips.map(c => c.assetId))].map(aid => manifest(db.assets.get(aid))), disclaimer: "Deterministic edit decision list; no production codec render is claimed." }; }
  function renderProject(projectId, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor"]); const edl = exportManifest(projectId, actorId); if (!edl.preview.clipCount) throw new DomainError("EMPTY_TIMELINE", "timeline requires at least one clip", 409); const rendered = renderTimelineVideo(p.timeline, edl.preview.duration); const asset = makeAsset({ project: p, kind: "video", role: "render", mimeType: "video/mp4", filename: `openreel-${p.id}-master.mp4`, bytes: rendered.bytes, metadata: { schema: "openreel-render/v1", duration: edl.preview.duration, sourceTimelineVersion: p.timeline.version, sha256: rendered.sha256, hasAudio: rendered.hasAudio, renderer: rendered.renderer, rendererVersion: "8.1", boundary: "deterministic local preview composition; no production codec quality claim" } }); sync(); return { schema: "openreel-render/v1", asset: manifest(asset), duration: edl.preview.duration, playable: true, productionReady: false, hasAudio: rendered.hasAudio, sha256: rendered.sha256, boundary: asset.metadata.boundary }; }
  function snapshot(projectId, actorId = "local-owner") { const p = get(db.projects, projectId, "project"); authorize(p, actorId, ["owner", "editor", "viewer"]); const jobs = [...db.jobs.values()].filter(j => j.projectId === p.id); return { project: clone(p), sessions: p.sessionIds.map(x => clone(db.sessions.get(x))), nodes: p.nodeIds.map(x => ({ ...clone(db.nodes.get(x)), runs: clone(jobs.filter(j => j.nodeId === x)), resultVersions: p.assetIds.map(aid => db.assets.get(aid)).filter(a => a.nodeId === x && a.role === "result").map(manifest) })), edges: p.edgeIds.map(x => clone(db.edges.get(x))), groups: p.groupIds.map(x => clone(db.groups.get(x))), jobs: clone(jobs), assets: p.assetIds.map(x => manifest(db.assets.get(x))), story: clone(p.story || null), storyboard: clone(p.storyboard || null), timeline: clone(p.timeline) }; }
  return { createUser, createProject, listProjects, updateProject, addMember, createSession, closeSession, createNode, updateNode, createEdge, updateEdge, createGroup, updateGroup, uploadReference, listAssets, listHistory, copyAsset, createJob, createArkCanvasJob, arkCanvasJob, reconcileArkCanvasJob, transitionJob, tickJob, progress, snapshot, assetManifest, assetContent, listModels, routeModel, upsertStory, upsertStoryboard, upsertTimeline, exportManifest, renderProject };
}

function initial() { return { schemaVersion: SCHEMA_VERSION, projects: [], sessions: [], nodes: [], edges: [], groups: [], jobs: [], assets: [], users: [] }; }
function load(file) { if (!file) return initial(); try { const raw = JSON.parse(readFileSync(file, "utf8")); if ([1, 2].includes(raw.schemaVersion)) raw.schemaVersion = 3; if (raw.schemaVersion !== SCHEMA_VERSION) throw new DomainError("UNSUPPORTED_SCHEMA", `unsupported schema version ${raw.schemaVersion}`, 500); for (const key of ["projects", "sessions", "nodes", "edges", "groups", "jobs", "assets", "users"]) raw[key] ||= []; for (const n of raw.nodes) n.position ||= { x: 0, y: 0 }; for (const p of raw.projects) { p.members ||= [{ userId: "local-owner", role: "owner" }]; p.edgeIds ||= raw.edges.filter(e => e.projectId === p.id).map(e => e.id); p.groupIds ||= raw.groups.filter(g => g.projectId === p.id).map(g => g.id); p.sceneIds ||= []; p.shotIds ||= []; p.timeline ||= { version: 1, tracks: [] }; } return raw; } catch (e) { if (e.code === "ENOENT") return initial(); throw e; } }
function reaches(start, target, projectId, edges) { const seen = new Set(), queue = [start]; while (queue.length) { const node = queue.shift(); if (node === target) return true; if (seen.has(node)) continue; seen.add(node); for (const edge of edges.values()) if (edge.projectId === projectId && edge.fromNodeId === node) queue.push(edge.toNodeId); } return false; }
function appendEvent(job, state, now, detail = {}) { job.events.push({ seq: job.events.length + 1, state, at: now(), ...detail }); }
function safeFilename(v, fallback) { if (typeof v !== "string" || !v.trim()) return fallback; const n = v.trim().replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 128); return n === "." || n === ".." ? fallback : n; }
function positive(v, name) { const n = Number(v); if (!Number.isFinite(n) || n <= 0) throw new DomainError("INVALID_INPUT", `${name} must be positive`); return n; }
function nonnegative(v, name) { const n = Number(v); if (!Number.isFinite(n) || n < 0) throw new DomainError("INVALID_INPUT", `${name} must be non-negative`); return n; }
function resultFixture(job) { if (job.kind === "image") { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="100%" height="100%" fill="#171923"/><text x="32" y="188" fill="#ff6a3d" font-family="sans-serif" font-size="28">OpenReel deterministic result</text></svg>`; return { mimeType: "image/svg+xml", filename: `openreel-${job.id}.svg`, bytes: Buffer.from(svg) }; } if (job.kind === "audio") return { mimeType: "audio/wav", filename: `openreel-${job.id}.wav`, bytes: Buffer.from("524946462400000057415645666d74201000000001000100401f0000803e0000020010006461746100000000", "hex") }; return { mimeType: "video/mp4", filename: `openreel-${job.id}.mp4`, bytes: Buffer.from("000000186674797069736F6D0000020069736F6D69736F32", "hex") }; }
