import { createHash, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { DomainError } from "./core.js";

export const PLATFORM_SCHEMA = 5;
const DEFAULT_CURRENCY = "USD", DEFAULT_UNIT_SCALE = 10_000;
const clone = structuredClone;
const initial = () => ({ schemaVersion: PLATFORM_SCHEMA, accounts: [], sessions: [], teams: [], invites: [], wallets: [], ledger: [], workflows: [], automations: [], objects: [], subscriptions: [], keyApplications: [], apiKeys: [], usageReservations: [], usageLedger: [] });
export class LocalObjectAdapter { constructor(state) { this.state = state; } put(tenantId, key, value) { const old = this.state.objects.find(x => x.tenantId === tenantId && x.key === key); if (old) old.value = clone(value); else this.state.objects.push({ tenantId, key, value: clone(value) }); } get(tenantId, key) { return clone(this.state.objects.find(x => x.tenantId === tenantId && x.key === key)?.value); } }
export class LocalDatabaseAdapter { constructor(state) { this.state = state; } query(tenantId, collection) { return clone(this.state[collection].filter(x => x.tenantId === tenantId)); } }

export function createPlatform({ file = null, now = () => new Date().toISOString(), id = () => crypto.randomUUID(), sessionTtlMs = 1000 * 60 * 60 * 24 * 7 } = {}) {
  let state = load(file), objects = new LocalObjectAdapter(state), database = new LocalDatabaseAdapter(state);
  const persist = () => { if (!file) return; mkdirSync(dirname(file), { recursive: true }); const tmp = `${file}.tmp`; writeFileSync(tmp, JSON.stringify(state)); renameSync(tmp, file); };
  const get = (items, rid, kind) => { const item = items.find(x => x.id === rid); if (!item) throw new DomainError("NOT_FOUND", `${kind} not found`, 404); return item; };
  const register = ({ email, password } = {}) => { const normalizedEmail = validEmail(email); if (typeof password !== "string" || password.length < 8 || password.length > 256) throw new DomainError("INVALID_CREDENTIALS", "password must contain 8 to 256 characters"); if (state.accounts.some(x => x.email === normalizedEmail)) throw new DomainError("CONFLICT", "account already exists", 409); const salt = randomBytes(16).toString("hex"), account = { id: id(), email: normalizedEmail, passwordHash: hash(password, salt), salt, createdAt: now() }; state.accounts.push(account); persist(); return publicAccount(account); };
  const login = ({ email, password } = {}) => { const account = state.accounts.find(x => typeof email === "string" && x.email === email.toLowerCase()); const candidate = account && typeof password === "string" && hash(password, account.salt); if (!account || !candidate || !timingSafeEqual(Buffer.from(candidate), Buffer.from(account.passwordHash))) throw new DomainError("INVALID_CREDENTIALS", "invalid email or password", 401); const token = randomBytes(32).toString("base64url"), createdAt = now(), session = { id: id(), accountId: account.id, tokenHash: tokenHash(token), createdAt, expiresAt: new Date(Date.parse(createdAt) + sessionTtlMs).toISOString(), revokedAt: null }; state.sessions.push(session); persist(); return { id: session.id, accountId: session.accountId, token, createdAt, expiresAt: session.expiresAt }; };
  const sessionFor = token => { if (typeof token !== "string" || !token) throw new DomainError("UNAUTHENTICATED", "valid session required", 401); const digest = tokenHash(token), session = state.sessions.find(x => x.tokenHash === digest && !x.revokedAt); if (!session || Date.parse(session.expiresAt) <= Date.parse(now())) throw new DomainError("UNAUTHENTICATED", "session is invalid or expired", 401); return session; };
  const authenticate = token => { const session = sessionFor(token); return publicAccount(get(state.accounts, session.accountId, "account")); };
  const logout = token => { const session = sessionFor(token); session.revokedAt = now(); persist(); return { loggedOut: true }; };
  const rotateSession = token => { const old = sessionFor(token); old.revokedAt = now(); const account = get(state.accounts, old.accountId, "account"), nextToken = randomBytes(32).toString("base64url"), createdAt = now(), session = { id: id(), accountId: account.id, tokenHash: tokenHash(nextToken), createdAt, expiresAt: new Date(Date.parse(createdAt) + sessionTtlMs).toISOString(), revokedAt: null }; state.sessions.push(session); persist(); return { id: session.id, accountId: session.accountId, token: nextToken, createdAt, expiresAt: session.expiresAt }; };
  const grantSubscription = (accountId, { plan = "pro", hardLimitUnits, hardLimitMicros, currency = DEFAULT_CURRENCY, unitScale = DEFAULT_UNIT_SCALE, periodEndsAt } = {}) => { get(state.accounts, accountId, "account"); const limit = nonNegativeInt(hardLimitUnits ?? hardLimitMicros, "hardLimitUnits"), money = moneyMeta(currency, unitScale); if (!periodEndsAt || !Number.isFinite(Date.parse(periodEndsAt)) || Date.parse(periodEndsAt) <= Date.parse(now())) throw new DomainError("INVALID_INPUT", "periodEndsAt must be a future timestamp"); let subscription = state.subscriptions.find(x => x.accountId === accountId && x.status === "active"); if (subscription && (subscription.currency !== money.currency || subscription.unitScale !== money.unitScale)) { subscription.status = "stopped"; subscription.updatedAt = now(); subscription.stoppedAt = now(); subscription.stopReason = "currency_version_replaced"; for (const key of state.apiKeys.filter(x => x.subscriptionId === subscription.id && x.status === "active")) { key.status = "suspended"; key.suspendedAt = now(); key.suspendReason = "currency_version_replaced"; } subscription = null; } if (subscription) Object.assign(subscription, { plan: text(plan, "plan"), hardLimitMicros: limit, currency: money.currency, unitScale: money.unitScale, periodEndsAt, updatedAt: now() }); else { subscription = { id: id(), accountId, plan: text(plan, "plan"), status: "active", hardLimitMicros: limit, currency: money.currency, unitScale: money.unitScale, spentMicros: 0, reservedMicros: 0, periodStartedAt: now(), periodEndsAt, createdAt: now(), updatedAt: now() }; state.subscriptions.push(subscription); } persist(); return clone(subscription); };
  const submitKeyApplication = (token, { reason, requestedLimitUnits, requestedLimitMicros, currency = DEFAULT_CURRENCY, unitScale = DEFAULT_UNIT_SCALE } = {}) => { const account = authenticate(token), money = moneyMeta(currency, unitScale), limit = positiveInt(requestedLimitUnits ?? requestedLimitMicros, "requestedLimitUnits"); if (state.keyApplications.some(x => x.accountId === account.id && x.status === "pending")) throw new DomainError("CONFLICT", "a pending key application already exists", 409); const application = { id: id(), accountId: account.id, email: account.email, reason: boundedText(reason, "reason", 1000), requestedLimitMicros: limit, requestedLimitUnits: limit, currency: money.currency, unitScale: money.unitScale, status: "pending", createdAt: now(), updatedAt: now(), reviewedAt: null, reviewedBy: null, reviewNote: null, subscriptionId: null }; state.keyApplications.push(application); persist(); return clone(application); };
  const listOwnKeyApplications = token => { const account = authenticate(token); return state.keyApplications.filter(x => x.accountId === account.id).map(x => clone(x)); };
  const listKeyApplications = ({ status } = {}) => state.keyApplications.filter(x => !status || x.status === status).map(x => clone(x));
  const approveKeyApplication = (applicationId, { plan = "pro", hardLimitUnits, hardLimitMicros, currency, unitScale, periodEndsAt, reviewNote = "Approved", reviewedBy = "administrator" } = {}) => { const application = get(state.keyApplications, applicationId, "key application"); if (application.status !== "pending") throw new DomainError("CONFLICT", "only pending applications can be approved", 409); const requestedMoney = moneyMeta(application.currency, application.unitScale), approvedMoney = moneyMeta(currency ?? requestedMoney.currency, unitScale ?? requestedMoney.unitScale); if (approvedMoney.currency !== requestedMoney.currency || approvedMoney.unitScale !== requestedMoney.unitScale) throw new DomainError("CURRENCY_MISMATCH", "approval currency must match the application", 409); const subscription = grantSubscription(application.accountId, { plan, hardLimitUnits, hardLimitMicros, ...approvedMoney, periodEndsAt }); Object.assign(application, { status: "approved", updatedAt: now(), reviewedAt: now(), reviewedBy: text(reviewedBy, "reviewedBy"), reviewNote: boundedText(reviewNote, "reviewNote", 1000), subscriptionId: subscription.id }); persist(); return { application: clone(application), subscription } };
  const rejectKeyApplication = (applicationId, { reviewNote, reviewedBy = "administrator" } = {}) => { const application = get(state.keyApplications, applicationId, "key application"); if (application.status !== "pending") throw new DomainError("CONFLICT", "only pending applications can be rejected", 409); Object.assign(application, { status: "rejected", updatedAt: now(), reviewedAt: now(), reviewedBy: text(reviewedBy, "reviewedBy"), reviewNote: boundedText(reviewNote, "reviewNote", 1000) }); persist(); return clone(application); };
  const stopKeyAccess = (applicationId, { reviewNote, reviewedBy = "administrator" } = {}) => { const application = get(state.keyApplications, applicationId, "key application"); if (application.status !== "approved") throw new DomainError("CONFLICT", "only approved access can be stopped", 409); const subscription = get(state.subscriptions, application.subscriptionId, "subscription"); subscription.status = "stopped"; subscription.updatedAt = now(); subscription.stoppedAt = now(); subscription.stopReason = boundedText(reviewNote, "reviewNote", 1000); for (const key of state.apiKeys.filter(x => x.accountId === application.accountId && x.status === "active")) { key.status = "suspended"; key.suspendedAt = now(); key.suspendReason = "access_stopped"; } Object.assign(application, { status: "stopped", updatedAt: now(), reviewedAt: now(), reviewedBy: text(reviewedBy, "reviewedBy"), reviewNote: subscription.stopReason }); persist(); return { application: clone(application), subscription: clone(subscription), keys: state.apiKeys.filter(x => x.accountId === application.accountId).map(publicApiKey) }; };
  const subscriptionFor = accountId => { const subscription = state.subscriptions.find(x => x.accountId === accountId && x.status === "active"); if (!subscription || Date.parse(subscription.periodEndsAt) <= Date.parse(now())) throw new DomainError("PAYMENT_REQUIRED", "an active paid subscription is required", 402); return subscription; };
  const createApiKey = (token, { name = "default" } = {}) => { const account = authenticate(token), subscription = subscriptionFor(account.id); if (subscription.spentMicros + subscription.reservedMicros >= subscription.hardLimitMicros) throw new DomainError("BUDGET_EXHAUSTED", "subscription hard limit reached", 402); const secret = `or_live_${randomBytes(32).toString("base64url")}`, prefix = secret.slice(0, 16), apiKey = { id: id(), accountId: account.id, subscriptionId: subscription.id, name: text(name, "name"), prefix, secretHash: tokenHash(secret), status: "active", createdAt: now(), lastUsedAt: null, revokedAt: null, suspendedAt: null, suspendReason: null }; state.apiKeys.push(apiKey); persist(); return { ...publicApiKey(apiKey), key: secret }; };
  const listApiKeys = token => { const account = authenticate(token); return state.apiKeys.filter(x => x.accountId === account.id).map(publicApiKey); };
  const revokeApiKey = (token, keyId) => { const account = authenticate(token), apiKey = get(state.apiKeys, keyId, "api key"); if (apiKey.accountId !== account.id) throw new DomainError("FORBIDDEN", "api key does not belong to this account", 403); apiKey.status = "revoked"; apiKey.revokedAt = now(); persist(); return publicApiKey(apiKey); };
  const authenticateApiKey = secret => { if (typeof secret !== "string" || !secret.startsWith("or_live_")) throw new DomainError("INVALID_API_KEY", "valid API key required", 401); const digest = tokenHash(secret), apiKey = state.apiKeys.find(x => x.secretHash === digest); if (!apiKey || apiKey.status !== "active") throw new DomainError("INVALID_API_KEY", "API key is invalid or inactive", 401); const subscription = subscriptionFor(apiKey.accountId); if (subscription.spentMicros >= subscription.hardLimitMicros) { apiKey.status = "suspended"; apiKey.suspendedAt = now(); apiKey.suspendReason = "hard_limit_reached"; persist(); throw new DomainError("BUDGET_EXHAUSTED", "subscription hard limit reached", 402); } apiKey.lastUsedAt = now(); persist(); return { apiKey: publicApiKey(apiKey), account: publicAccount(get(state.accounts, apiKey.accountId, "account")), subscription: clone(subscription) }; };
  const reserveUsageFor = (accountId, apiKeyId, { model, maxCostMicros, pricingVersion = null, currency = DEFAULT_CURRENCY, unitScale = DEFAULT_UNIT_SCALE, idempotencyKey } = {}) => { get(state.accounts, accountId, "account"); const subscription = subscriptionFor(accountId), money = moneyMeta(currency, unitScale); if (subscription.currency !== money.currency || subscription.unitScale !== money.unitScale) throw new DomainError("CURRENCY_MISMATCH", "subscription currency does not match model pricing", 409); const amount = nonNegativeInt(maxCostMicros, "maxCostMicros"); if (!idempotencyKey) throw new DomainError("INVALID_INPUT", "idempotencyKey is required"); const replay = state.usageReservations.find(x => x.accountId === accountId && (x.apiKeyId || null) === (apiKeyId || null) && x.idempotencyKey === idempotencyKey); if (replay) return clone(replay); if (subscription.spentMicros + subscription.reservedMicros + amount > subscription.hardLimitMicros) throw new DomainError("BUDGET_EXHAUSTED", "request would exceed subscription hard limit", 402); subscription.reservedMicros += amount; const reservation = { id: id(), apiKeyId: apiKeyId || null, accountId, subscriptionId: subscription.id, model: text(model, "model"), pricingVersion: pricingVersion ? text(pricingVersion, "pricingVersion") : null, currency: money.currency, unitScale: money.unitScale, maxCostMicros: amount, status: "reserved", idempotencyKey, createdAt: now() }; state.usageReservations.push(reservation); persist(); return clone(reservation); };
  const reserveUsage = (secret, request = {}) => { const { apiKey } = authenticateApiKey(secret); return reserveUsageFor(apiKey.accountId, apiKey.id, request); };
  const reserveUsageForAccount = (accountId, request = {}) => reserveUsageFor(accountId, null, request);
  const settleUsageFor = (accountId, apiKeyId, reservationId, { inputTokens = 0, outputTokens = 0, inputMicrosPerMillion, outputMicrosPerMillion, pricingVersion = null, failed = false } = {}) => { const reservation = get(state.usageReservations, reservationId, "usage reservation"); if (reservation.accountId !== accountId || (reservation.apiKeyId || null) !== (apiKeyId || null)) throw new DomainError("FORBIDDEN", "reservation does not belong to this billing principal", 403); const old = state.usageLedger.find(x => x.reservationId === reservation.id); if (old) return clone(old); if (reservation.status !== "reserved") throw new DomainError("CONFLICT", "usage reservation is not open", 409); if ((reservation.pricingVersion || null) !== (pricingVersion || null)) throw new DomainError("PRICING_VERSION_MISMATCH", "settlement pricing version differs from reservation", 409); const subscription = get(state.subscriptions, reservation.subscriptionId, "subscription"), input = nonNegativeInt(inputTokens, "inputTokens"), output = nonNegativeInt(outputTokens, "outputTokens"), inRate = nonNegativeInt(inputMicrosPerMillion, "inputMicrosPerMillion"), outRate = nonNegativeInt(outputMicrosPerMillion, "outputMicrosPerMillion"); const costMicros = failed ? 0 : Math.ceil((input * inRate + output * outRate) / 1_000_000); if (costMicros > reservation.maxCostMicros) throw new DomainError("USAGE_EXCEEDS_RESERVATION", "reported usage exceeds reserved maximum", 409); subscription.reservedMicros -= reservation.maxCostMicros; subscription.spentMicros += costMicros; reservation.status = failed ? "failed" : "settled"; const entry = { id: id(), reservationId: reservation.id, apiKeyId: apiKeyId || null, accountId, subscriptionId: subscription.id, model: reservation.model, pricingVersion: reservation.pricingVersion || null, currency: reservation.currency, unitScale: reservation.unitScale, inputTokens: input, outputTokens: output, inputMicrosPerMillion: inRate, outputMicrosPerMillion: outRate, costMicros, status: reservation.status, createdAt: now() }; state.usageLedger.push(entry); if (subscription.spentMicros >= subscription.hardLimitMicros) { for (const key of state.apiKeys.filter(x => x.accountId === subscription.accountId && x.status === "active")) { key.status = "suspended"; key.suspendedAt = now(); key.suspendReason = "hard_limit_reached"; } } persist(); return clone(entry); };
  const settleUsage = (secret, reservationId, result = {}) => { const { apiKey } = authenticateApiKey(secret); return settleUsageFor(apiKey.accountId, apiKey.id, reservationId, result); };
  const settleUsageForAccount = (accountId, reservationId, result = {}) => settleUsageFor(accountId, null, reservationId, result);
  const usageStatus = token => { const account = authenticate(token), subscription = subscriptionFor(account.id); return { subscription: clone(subscription), keys: state.apiKeys.filter(x => x.accountId === account.id).map(publicApiKey), usage: state.usageLedger.filter(x => x.accountId === account.id).map(x => clone(x)) }; };
  const createTeam = (token, { name }) => { const account = authenticate(token), team = { id: id(), name: text(name, "name"), tenantId: id(), members: [{ accountId: account.id, role: "owner" }], version: 1, createdAt: now() }; state.teams.push(team); state.wallets.push({ tenantId: team.tenantId, plan: "local", balance: 10000, reserved: 0, ceiling: 10000 }); persist(); return clone(team); };
  const role = (token, teamId, allowed) => { const account = authenticate(token), team = get(state.teams, teamId, "team"), membership = team.members.find(x => x.accountId === account.id); if (!membership || !allowed.includes(membership.role)) throw new DomainError("FORBIDDEN", "team role does not allow this operation", 403); return { account, team, membership }; };
  const invite = (token, teamId, { email, role: invitedRole = "viewer" } = {}) => { const { team } = role(token, teamId, ["owner", "admin"]), normalizedEmail = validEmail(email); if (!new Set(["admin", "editor", "viewer"]).has(invitedRole)) throw new DomainError("INVALID_INPUT", "invalid team role"); if (state.invites.some(x => x.teamId === teamId && x.email === normalizedEmail && x.status === "pending")) throw new DomainError("CONFLICT", "pending invite already exists", 409); const invite = { id: id(), teamId, tenantId: team.tenantId, email: normalizedEmail, role: invitedRole, status: "pending", createdAt: now() }; state.invites.push(invite); persist(); return clone(invite); };
  const acceptInvite = (token, inviteId) => { const account = authenticate(token), invite = get(state.invites, inviteId, "invite"), team = get(state.teams, invite.teamId, "team"); if (invite.status !== "pending" || invite.email !== account.email) throw new DomainError("FORBIDDEN", "invite cannot be accepted", 403); if (team.members.some(x => x.accountId === account.id)) throw new DomainError("CONFLICT", "already a member", 409); team.members.push({ accountId: account.id, role: invite.role }); invite.status = "accepted"; team.version++; persist(); return clone(team); };
  const quote = (token, teamId, spec = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), units = positiveInt(spec.units ?? 1, "units"), unitPrice = ({ image: 10, video: 40, audio: 5 })[spec.kind]; if (!unitPrice) throw new DomainError("INVALID_INPUT", "unsupported quote kind"); return { schema: "openreel-quote/v1", tenantId: team.tenantId, kind: spec.kind, units, amount: units * unitPrice, currency: "local-credit", pricingVersion: 1 }; };
  const reserve = (token, teamId, spec = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), q = quote(token, teamId, spec), wallet = walletFor(team.tenantId); if (q.amount > wallet.balance - wallet.reserved || wallet.reserved + q.amount > wallet.ceiling) throw new DomainError("INSUFFICIENT_BUDGET", "hard budget ceiling exceeded", 409); const replay = spec.idempotencyKey && state.ledger.find(x => x.tenantId === team.tenantId && x.idempotencyKey === spec.idempotencyKey && x.type === "reservation"); if (replay) return clone(replay); wallet.reserved += q.amount; const entry = { id: id(), tenantId: team.tenantId, type: "reservation", amount: q.amount, status: "reserved", quote: q, idempotencyKey: spec.idempotencyKey || null, createdAt: now() }; state.ledger.push(entry); persist(); return clone(entry); };
  const settle = (token, teamId, reservationId, { actualAmount, failure = null } = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), reservation = get(state.ledger, reservationId, "reservation"), wallet = walletFor(team.tenantId); if (reservation.tenantId !== team.tenantId) throw new DomainError("FORBIDDEN", "cross-tenant ledger access denied", 403); if (reservation.status !== "reserved") return clone(state.ledger.find(x => x.reservationId === reservation.id)); const amount = failure ? 0 : Number(actualAmount ?? reservation.amount); if (!Number.isFinite(amount) || amount < 0 || amount > reservation.amount) throw new DomainError("INVALID_SETTLEMENT", "actual cost must be within reservation"); wallet.reserved -= reservation.amount; wallet.balance -= amount; reservation.status = failure ? "failed" : "settled"; const entry = { id: id(), tenantId: team.tenantId, reservationId: reservation.id, type: "settlement", amount, status: reservation.status, failure, createdAt: now() }; state.ledger.push(entry); persist(); return clone(entry); };
  const budgetStatus = (token, teamId) => { const { team } = role(token, teamId, ["owner", "admin", "editor", "viewer"]); return { ...clone(walletFor(team.tenantId)), ledger: database.query(team.tenantId, "ledger") }; };
  const importWorkflow = (token, teamId, document) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]); validateWorkflow(document); const digest = createHash("sha256").update(JSON.stringify(document)).digest("hex"), old = state.workflows.find(x => x.tenantId === team.tenantId && x.digest === digest); if (old) return clone(old); const workflow = { id: id(), tenantId: team.tenantId, schema: document.schema, template: document.template, version: document.version, nodes: clone(document.nodes), digest, provenance: { importedAt: now(), source: "local-import" } }; state.workflows.push(workflow); persist(); return clone(workflow); };
  const planAutomation = (token, teamId, { intent, workflowId }) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), workflow = get(state.workflows, workflowId, "workflow"); if (workflow.tenantId !== team.tenantId) throw new DomainError("FORBIDDEN", "cross-tenant workflow denied", 403); return { schema: "openreel-automation-plan/v1", tenantId: team.tenantId, intent: text(intent, "intent"), workflowId, nodes: workflow.nodes.map((node, order) => ({ ...clone(node), order })), estimatedCost: workflow.nodes.length * 10 }; };
  const runAutomation = (token, teamId, plan, idempotencyKey) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]); if (!idempotencyKey) throw new DomainError("INVALID_INPUT", "idempotencyKey is required"); const old = state.automations.find(x => x.tenantId === team.tenantId && x.idempotencyKey === idempotencyKey); if (old) return clone(old); const reservation = reserve(token, teamId, { kind: "image", units: plan.nodes.length, idempotencyKey: `automation:${idempotencyKey}` }); const failedNode = plan.nodes.find(x => x.fail === true), run = { id: id(), tenantId: team.tenantId, idempotencyKey, intent: plan.intent, plan: clone(plan), status: failedNode ? "failed" : "succeeded", failure: failedNode ? { nodeId: failedNode.id, code: "NODE_FAILED" } : null, cost: failedNode ? 0 : reservation.amount, reservationId: reservation.id, createdAt: now() }; settle(token, teamId, reservation.id, { actualAmount: run.cost, failure: run.failure }); state.automations.push(run); persist(); return clone(run); };
  const walletFor = tenantId => { const wallet = state.wallets.find(x => x.tenantId === tenantId); if (!wallet) throw new DomainError("NOT_FOUND", "wallet not found", 404); return wallet; };
  return { register, login, logout, rotateSession, authenticate, grantSubscription, submitKeyApplication, listOwnKeyApplications, listKeyApplications, approveKeyApplication, rejectKeyApplication, stopKeyAccess, createApiKey, listApiKeys, revokeApiKey, authenticateApiKey, reserveUsage, reserveUsageForAccount, settleUsage, settleUsageForAccount, usageStatus, createTeam, invite, acceptInvite, quote, reserve, settle, budgetStatus, importWorkflow, planAutomation, runAutomation, objects, database, securityBoundary: () => ({ productionReady: false, boundary: "Provider credentials remain server-side. Browser workspaces use authenticated account entitlements; external API clients use hashed platform keys. Both paths share reservation, pricing, and usage settlement. Payment-provider callbacks and distributed accounting are not yet connected." }) };
}
function load(file) { if (!file) return initial(); try { const value = JSON.parse(readFileSync(file, "utf8")); if (value.schemaVersion === 1) { value.schemaVersion = 2; value.sessions = []; } if (value.schemaVersion === 2) { value.schemaVersion = 3; value.subscriptions = []; value.apiKeys = []; value.usageReservations = []; value.usageLedger = []; } if (value.schemaVersion === 3) { value.schemaVersion = 4; value.keyApplications = []; } if (value.schemaVersion === 4) { for (const item of [...value.subscriptions, ...value.keyApplications, ...value.usageReservations, ...value.usageLedger]) { item.currency ||= "CNY"; item.unitScale ||= 1_000_000; } for (const item of value.keyApplications) item.requestedLimitUnits ??= item.requestedLimitMicros; value.schemaVersion = 5; } if (value.schemaVersion !== PLATFORM_SCHEMA) throw new DomainError("UNSUPPORTED_SCHEMA", "unsupported platform schema", 500); return value; } catch (error) { if (error.code === "ENOENT") return initial(); throw error; } }
function hash(password, salt) { return scryptSync(password, salt, 32).toString("hex"); }
function tokenHash(token) { return createHash("sha256").update(token).digest("hex"); }
function publicAccount({ passwordHash, salt, ...account }) { return clone(account); }
function publicApiKey({ secretHash, ...apiKey }) { return clone(apiKey); }
function validEmail(value) { if (typeof value !== "string" || value.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) throw new DomainError("INVALID_CREDENTIALS", "a valid email is required"); return value.toLowerCase(); }
function text(value, field) { if (typeof value !== "string" || !value.trim()) throw new DomainError("INVALID_INPUT", `${field} is required`); return value.trim(); }
function boundedText(value, field, max) { const result = text(value, field); if (result.length > max) throw new DomainError("INVALID_INPUT", `${field} must be at most ${max} characters`); return result; }
function positiveInt(value, field) { const n = Number(value); if (!Number.isInteger(n) || n <= 0) throw new DomainError("INVALID_INPUT", `${field} must be a positive integer`); return n; }
function nonNegativeInt(value, field) { const n = Number(value); if (!Number.isSafeInteger(n) || n < 0) throw new DomainError("INVALID_INPUT", `${field} must be a non-negative safe integer`); return n; }
function moneyMeta(currency, unitScale) { if (currency !== "USD" && currency !== "CNY") throw new DomainError("INVALID_INPUT", "currency must be USD or CNY"); const scale = positiveInt(unitScale, "unitScale"); if ((currency === "USD" && scale !== 10_000) || (currency === "CNY" && scale !== 1_000_000)) throw new DomainError("INVALID_INPUT", "unsupported currency precision"); return { currency, unitScale: scale }; }
function validateWorkflow(value) { if (value?.schema !== "openreel-workflow/v1" || !Number.isInteger(value.version) || value.version < 1 || !value.template?.trim() || !Array.isArray(value.nodes) || !value.nodes.length) throw new DomainError("INVALID_WORKFLOW", "workflow must be a versioned openreel-workflow/v1 document with template and nodes", 422); for (const node of value.nodes) if (!node.id || !["script", "image", "video", "audio"].includes(node.type)) throw new DomainError("INVALID_WORKFLOW", "workflow node is invalid", 422); }
