import { createHash, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { DomainError } from "./core.js";

export const PLATFORM_SCHEMA = 2;
const clone = structuredClone;
const initial = () => ({ schemaVersion: PLATFORM_SCHEMA, accounts: [], sessions: [], teams: [], invites: [], wallets: [], ledger: [], workflows: [], automations: [], objects: [] });
export class LocalObjectAdapter { constructor(state) { this.state = state; } put(tenantId, key, value) { const old = this.state.objects.find(x => x.tenantId === tenantId && x.key === key); if (old) old.value = clone(value); else this.state.objects.push({ tenantId, key, value: clone(value) }); } get(tenantId, key) { return clone(this.state.objects.find(x => x.tenantId === tenantId && x.key === key)?.value); } }
export class LocalDatabaseAdapter { constructor(state) { this.state = state; } query(tenantId, collection) { return clone(this.state[collection].filter(x => x.tenantId === tenantId)); } }

export function createPlatform({ file = null, now = () => new Date().toISOString(), id = () => crypto.randomUUID(), sessionTtlMs = 1000 * 60 * 60 * 24 * 7 } = {}) {
  let state = load(file), objects = new LocalObjectAdapter(state), database = new LocalDatabaseAdapter(state);
  const persist = () => { if (!file) return; mkdirSync(dirname(file), { recursive: true }); const tmp = `${file}.tmp`; writeFileSync(tmp, JSON.stringify(state)); renameSync(tmp, file); };
  const get = (items, rid, kind) => { const item = items.find(x => x.id === rid); if (!item) throw new DomainError("NOT_FOUND", `${kind} not found`, 404); return item; };
  const register = ({ email, password } = {}) => { const normalizedEmail = validEmail(email); if (typeof password !== "string" || password.length < 8 || password.length > 256) throw new DomainError("INVALID_CREDENTIALS", "password must contain 8 to 256 characters"); if (state.accounts.some(x => x.email === normalizedEmail)) throw new DomainError("CONFLICT", "account already exists", 409); const salt = randomBytes(16).toString("hex"), account = { id: id(), email: normalizedEmail, passwordHash: hash(password, salt), salt, createdAt: now() }; state.accounts.push(account); persist(); return publicAccount(account); };
  const login = ({ email, password } = {}) => { const account = state.accounts.find(x => typeof email === "string" && x.email === email.toLowerCase()); const candidate = account && typeof password === "string" && hash(password, account.salt); if (!account || !candidate || !timingSafeEqual(Buffer.from(candidate), Buffer.from(account.passwordHash))) throw new DomainError("INVALID_CREDENTIALS", "invalid email or password", 401); const token = randomBytes(32).toString("base64url"), createdAt = now(), session = { id: id(), accountId: account.id, tokenHash: tokenHash(token), createdAt, expiresAt: new Date(Date.parse(createdAt) + sessionTtlMs).toISOString(), revokedAt: null }; state.sessions.push(session); persist(); return { id: session.id, accountId: session.accountId, token, createdAt, expiresAt: session.expiresAt }; };
  const sessionFor = token => { if (typeof token !== "string" || !token) throw new DomainError("UNAUTHENTICATED", "valid session required", 401); const digest = tokenHash(token), session = state.sessions.find(x => x.tokenHash === digest && !x.revokedAt); if (!session || Date.parse(session.expiresAt) <= Date.parse(now())) throw new DomainError("UNAUTHENTICATED", "session is invalid or expired", 401); return session; };
  const authenticate = token => { const session = sessionFor(token); return publicAccount(get(state.accounts, session.accountId, "account")); };
  const logout = token => { const session = sessionFor(token); session.revokedAt = now(); persist(); return { loggedOut: true }; };
  const rotateSession = token => { const old = sessionFor(token); old.revokedAt = now(); const account = get(state.accounts, old.accountId, "account"), nextToken = randomBytes(32).toString("base64url"), createdAt = now(), session = { id: id(), accountId: account.id, tokenHash: tokenHash(nextToken), createdAt, expiresAt: new Date(Date.parse(createdAt) + sessionTtlMs).toISOString(), revokedAt: null }; state.sessions.push(session); persist(); return { id: session.id, accountId: session.accountId, token: nextToken, createdAt, expiresAt: session.expiresAt }; };
  const createTeam = (token, { name }) => { const account = authenticate(token), team = { id: id(), name: text(name, "name"), tenantId: id(), members: [{ accountId: account.id, role: "owner" }], version: 1, createdAt: now() }; state.teams.push(team); state.wallets.push({ tenantId: team.tenantId, plan: "local", balance: 10000, reserved: 0, ceiling: 10000 }); persist(); return clone(team); };
  const role = (token, teamId, allowed) => { const account = authenticate(token), team = get(state.teams, teamId, "team"), membership = team.members.find(x => x.accountId === account.id); if (!membership || !allowed.includes(membership.role)) throw new DomainError("FORBIDDEN", "team role does not allow this operation", 403); return { account, team, membership }; };
  const invite = (token, teamId, { email, role: invitedRole = "viewer" } = {}) => { const { team } = role(token, teamId, ["owner", "admin"]), normalizedEmail = validEmail(email); if (!new Set(["admin", "editor", "viewer"]).has(invitedRole)) throw new DomainError("INVALID_INPUT", "invalid team role"); if (state.invites.some(x => x.teamId === teamId && x.email === normalizedEmail && x.status === "pending")) throw new DomainError("CONFLICT", "pending invite already exists", 409); const invite = { id: id(), teamId, tenantId: team.tenantId, email: normalizedEmail, role: invitedRole, status: "pending", createdAt: now() }; state.invites.push(invite); persist(); return clone(invite); };
  const acceptInvite = (token, inviteId) => { const account = authenticate(token), invite = get(state.invites, inviteId, "invite"), team = get(state.teams, invite.teamId, "team"); if (invite.status !== "pending" || invite.email !== account.email) throw new DomainError("FORBIDDEN", "invite cannot be accepted", 403); if (team.members.some(x => x.accountId === account.id)) throw new DomainError("CONFLICT", "already a member", 409); team.members.push({ accountId: account.id, role: invite.role }); invite.status = "accepted"; team.version++; persist(); return clone(team); };
  const quote = (token, teamId, spec = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), units = positiveInt(spec.units ?? 1, "units"), unitPrice = ({ image: 10, video: 40, audio: 5 })[spec.kind]; if (!unitPrice) throw new DomainError("INVALID_INPUT", "unsupported quote kind"); return { schema: "openreel-quote/v1", tenantId: team.tenantId, kind: spec.kind, units, amount: units * unitPrice, currency: "local-credit", pricingVersion: 1 }; };
  const reserve = (token, teamId, spec = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), q = quote(token, teamId, spec), wallet = walletFor(team.tenantId); if (q.amount > wallet.balance - wallet.reserved || wallet.reserved + q.amount > wallet.ceiling) throw new DomainError("INSUFFICIENT_BUDGET", "hard budget ceiling exceeded", 409); const replay = spec.idempotencyKey && state.ledger.find(x => x.tenantId === team.tenantId && x.idempotencyKey === spec.idempotencyKey && x.type === "reservation"); if (replay) return clone(replay); wallet.reserved += q.amount; const entry = { id: id(), tenantId: team.tenantId, type: "reservation", amount: q.amount, status: "reserved", quote: q, idempotencyKey: spec.idempotencyKey || null, createdAt: now() }; state.ledger.push(entry); persist(); return clone(entry); };
  const settle = (token, teamId, reservationId, { actualAmount, failure = null } = {}) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), reservation = get(state.ledger, reservationId, "reservation"), wallet = walletFor(team.tenantId); if (reservation.tenantId !== team.tenantId) throw new DomainError("FORBIDDEN", "cross-tenant ledger access denied", 403); if (reservation.status !== "reserved") return clone(state.ledger.find(x => x.reservationId === reservation.id)); const amount = failure ? 0 : Number(actualAmount ?? reservation.amount); if (!Number.isFinite(amount) || amount < 0 || amount > reservation.amount) throw new DomainError("INVALID_SETTLEMENT", "actual cost must be within reservation"); wallet.reserved -= reservation.amount; wallet.balance -= amount; reservation.status = failure ? "failed" : "settled"; const entry = { id: id(), tenantId: team.tenantId, reservationId: reservation.id, type: "settlement", amount, status: reservation.status, failure, createdAt: now() }; state.ledger.push(entry); persist(); return clone(entry); };
  const budgetStatus = (token, teamId) => { const { team } = role(token, teamId, ["owner", "admin", "editor", "viewer"]); return { ...clone(walletFor(team.tenantId)), ledger: database.query(team.tenantId, "ledger") }; };
  const importWorkflow = (token, teamId, document) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]); validateWorkflow(document); const digest = createHash("sha256").update(JSON.stringify(document)).digest("hex"), old = state.workflows.find(x => x.tenantId === team.tenantId && x.digest === digest); if (old) return clone(old); const workflow = { id: id(), tenantId: team.tenantId, schema: document.schema, template: document.template, version: document.version, nodes: clone(document.nodes), digest, provenance: { importedAt: now(), source: "local-import" } }; state.workflows.push(workflow); persist(); return clone(workflow); };
  const planAutomation = (token, teamId, { intent, workflowId }) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]), workflow = get(state.workflows, workflowId, "workflow"); if (workflow.tenantId !== team.tenantId) throw new DomainError("FORBIDDEN", "cross-tenant workflow denied", 403); return { schema: "openreel-automation-plan/v1", tenantId: team.tenantId, intent: text(intent, "intent"), workflowId, nodes: workflow.nodes.map((node, order) => ({ ...clone(node), order })), estimatedCost: workflow.nodes.length * 10 }; };
  const runAutomation = (token, teamId, plan, idempotencyKey) => { const { team } = role(token, teamId, ["owner", "admin", "editor"]); if (!idempotencyKey) throw new DomainError("INVALID_INPUT", "idempotencyKey is required"); const old = state.automations.find(x => x.tenantId === team.tenantId && x.idempotencyKey === idempotencyKey); if (old) return clone(old); const reservation = reserve(token, teamId, { kind: "image", units: plan.nodes.length, idempotencyKey: `automation:${idempotencyKey}` }); const failedNode = plan.nodes.find(x => x.fail === true), run = { id: id(), tenantId: team.tenantId, idempotencyKey, intent: plan.intent, plan: clone(plan), status: failedNode ? "failed" : "succeeded", failure: failedNode ? { nodeId: failedNode.id, code: "NODE_FAILED" } : null, cost: failedNode ? 0 : reservation.amount, reservationId: reservation.id, createdAt: now() }; settle(token, teamId, reservation.id, { actualAmount: run.cost, failure: run.failure }); state.automations.push(run); persist(); return clone(run); };
  const walletFor = tenantId => { const wallet = state.wallets.find(x => x.tenantId === tenantId); if (!wallet) throw new DomainError("NOT_FOUND", "wallet not found", 404); return wallet; };
  return { register, login, logout, rotateSession, authenticate, createTeam, invite, acceptInvite, quote, reserve, settle, budgetStatus, importWorkflow, planAutomation, runAutomation, objects, database, securityBoundary: () => ({ productionReady: false, boundary: "Local-only authentication and storage; no TLS, key management, audit export, billing provider, distributed transaction, or production hardening." }) };
}
function load(file) { if (!file) return initial(); try { const value = JSON.parse(readFileSync(file, "utf8")); if (value.schemaVersion === 1) { value.schemaVersion = 2; value.sessions = []; } if (value.schemaVersion !== PLATFORM_SCHEMA) throw new DomainError("UNSUPPORTED_SCHEMA", "unsupported platform schema", 500); return value; } catch (error) { if (error.code === "ENOENT") return initial(); throw error; } }
function hash(password, salt) { return scryptSync(password, salt, 32).toString("hex"); }
function tokenHash(token) { return createHash("sha256").update(token).digest("hex"); }
function publicAccount({ passwordHash, salt, ...account }) { return clone(account); }
function validEmail(value) { if (typeof value !== "string" || value.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) throw new DomainError("INVALID_CREDENTIALS", "a valid email is required"); return value.toLowerCase(); }
function text(value, field) { if (typeof value !== "string" || !value.trim()) throw new DomainError("INVALID_INPUT", `${field} is required`); return value.trim(); }
function positiveInt(value, field) { const n = Number(value); if (!Number.isInteger(n) || n <= 0) throw new DomainError("INVALID_INPUT", `${field} must be a positive integer`); return n; }
function validateWorkflow(value) { if (value?.schema !== "openreel-workflow/v1" || !Number.isInteger(value.version) || value.version < 1 || !value.template?.trim() || !Array.isArray(value.nodes) || !value.nodes.length) throw new DomainError("INVALID_WORKFLOW", "workflow must be a versioned openreel-workflow/v1 document with template and nodes", 422); for (const node of value.nodes) if (!node.id || !["script", "image", "video", "audio"].includes(node.type)) throw new DomainError("INVALID_WORKFLOW", "workflow node is invalid", 422); }
